/**
 * This file was generated using Roro's parser
 * which parses language description in Wirth Notation into a Stack Automata in C.
 * https://github.com/rogerioyuuki/poli-github/tree/master/compiladores/entrega3/syntax
 *
 * Thanks [Roro](https://github.com/rogerioyuuki)!
 */

#include "ape.h"
#include "../lib/utarray.h"
#include "../lib/uthash.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/******************************/
/*          WARNING           */
/* This file is autogenerated */
/*                            */
/******************************/

void Automato_copy(void *_dst, const void *_src) {
  Automato *dst = (Automato*)_dst, *src = (Automato*)_src;
  dst->title = src->title;
  dst->estado = src->estado;

  dst->estadosTransicoes = src->estadosTransicoes;
  dst->estadosFinais = src->estadosFinais;
}

UT_icd Automato_icd = {sizeof(Automato), NULL, Automato_copy, NULL};

APE *create_ape() {
    int push_tmp;

    /* Initialize APE */
    APE * ape = malloc(sizeof(APE));
    ape->automatos = NULL;
    utarray_new(ape->pilha, &Automato_icd);



    /* PROGRAMA */

    Automato *PROGRAMA = malloc(sizeof(Automato));
    PROGRAMA->estadosTransicoes = NULL;
    PROGRAMA->title = "PROGRAMA";
    PROGRAMA->estado = 0;
    utarray_new(PROGRAMA->estadosFinais, &ut_int_icd);



    push_tmp = 5; utarray_push_back(PROGRAMA->estadosFinais, &push_tmp);



    Estado *PROGRAMA0 = malloc(sizeof(Estado));
    PROGRAMA0->transicoes = NULL;
    PROGRAMA0->chamadas = NULL;
    PROGRAMA0->estado = 0;
    HASH_ADD_INT(PROGRAMA->estadosTransicoes, estado, PROGRAMA0);


    Transicao *PROGRAMA0_T1 = malloc(sizeof(Transicao));
    PROGRAMA0_T1->token = "PROGRAM";
    PROGRAMA0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, PROGRAMA0->transicoes, PROGRAMA0_T1->token, strlen(PROGRAMA0_T1->token), PROGRAMA0_T1);



    Estado *PROGRAMA1 = malloc(sizeof(Estado));
    PROGRAMA1->transicoes = NULL;
    PROGRAMA1->chamadas = NULL;
    PROGRAMA1->estado = 1;
    HASH_ADD_INT(PROGRAMA->estadosTransicoes, estado, PROGRAMA1);



    TransicaoChamada *PROGRAMA1_C1 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C1->token = "OUTPUT";
    PROGRAMA1_C1->submaquina = "bloco";
    PROGRAMA1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C1->token, strlen(PROGRAMA1_C1->token), PROGRAMA1_C1);

    TransicaoChamada *PROGRAMA1_C2 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C2->token = "CALL";
    PROGRAMA1_C2->submaquina = "bloco";
    PROGRAMA1_C2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C2->token, strlen(PROGRAMA1_C2->token), PROGRAMA1_C2);

    TransicaoChamada *PROGRAMA1_C3 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C3->token = "WHILE";
    PROGRAMA1_C3->submaquina = "bloco";
    PROGRAMA1_C3->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C3->token, strlen(PROGRAMA1_C3->token), PROGRAMA1_C3);

    TransicaoChamada *PROGRAMA1_C4 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C4->token = "VAR";
    PROGRAMA1_C4->submaquina = "bloco";
    PROGRAMA1_C4->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C4->token, strlen(PROGRAMA1_C4->token), PROGRAMA1_C4);

    TransicaoChamada *PROGRAMA1_C5 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C5->token = "FUNCTION";
    PROGRAMA1_C5->submaquina = "bloco";
    PROGRAMA1_C5->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C5->token, strlen(PROGRAMA1_C5->token), PROGRAMA1_C5);

    TransicaoChamada *PROGRAMA1_C6 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C6->token = "id";
    PROGRAMA1_C6->submaquina = "bloco";
    PROGRAMA1_C6->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C6->token, strlen(PROGRAMA1_C6->token), PROGRAMA1_C6);

    TransicaoChamada *PROGRAMA1_C7 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C7->token = "INPUT";
    PROGRAMA1_C7->submaquina = "bloco";
    PROGRAMA1_C7->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C7->token, strlen(PROGRAMA1_C7->token), PROGRAMA1_C7);

    TransicaoChamada *PROGRAMA1_C8 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C8->token = "IF";
    PROGRAMA1_C8->submaquina = "bloco";
    PROGRAMA1_C8->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C8->token, strlen(PROGRAMA1_C8->token), PROGRAMA1_C8);


    Estado *PROGRAMA2 = malloc(sizeof(Estado));
    PROGRAMA2->transicoes = NULL;
    PROGRAMA2->chamadas = NULL;
    PROGRAMA2->estado = 2;
    HASH_ADD_INT(PROGRAMA->estadosTransicoes, estado, PROGRAMA2);


    Transicao *PROGRAMA2_T1 = malloc(sizeof(Transicao));
    PROGRAMA2_T1->token = "END";
    PROGRAMA2_T1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, PROGRAMA2->transicoes, PROGRAMA2_T1->token, strlen(PROGRAMA2_T1->token), PROGRAMA2_T1);



    Estado *PROGRAMA3 = malloc(sizeof(Estado));
    PROGRAMA3->transicoes = NULL;
    PROGRAMA3->chamadas = NULL;
    PROGRAMA3->estado = 3;
    HASH_ADD_INT(PROGRAMA->estadosTransicoes, estado, PROGRAMA3);


    Transicao *PROGRAMA3_T1 = malloc(sizeof(Transicao));
    PROGRAMA3_T1->token = "PROGRAM";
    PROGRAMA3_T1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, PROGRAMA3->transicoes, PROGRAMA3_T1->token, strlen(PROGRAMA3_T1->token), PROGRAMA3_T1);



    Estado *PROGRAMA4 = malloc(sizeof(Estado));
    PROGRAMA4->transicoes = NULL;
    PROGRAMA4->chamadas = NULL;
    PROGRAMA4->estado = 4;
    HASH_ADD_INT(PROGRAMA->estadosTransicoes, estado, PROGRAMA4);


    Transicao *PROGRAMA4_T1 = malloc(sizeof(Transicao));
    PROGRAMA4_T1->token = ";";
    PROGRAMA4_T1->estadoResultado = 5;
    HASH_ADD_KEYPTR(hh, PROGRAMA4->transicoes, PROGRAMA4_T1->token, strlen(PROGRAMA4_T1->token), PROGRAMA4_T1);




    HASH_ADD_KEYPTR(hh, ape->automatos, PROGRAMA->title, strlen(PROGRAMA->title), PROGRAMA);


    ape->automatoAtual = PROGRAMA;



    /* bloco */

    Automato *bloco = malloc(sizeof(Automato));
    bloco->estadosTransicoes = NULL;
    bloco->title = "bloco";
    bloco->estado = 0;
    utarray_new(bloco->estadosFinais, &ut_int_icd);



    push_tmp = 3; utarray_push_back(bloco->estadosFinais, &push_tmp);



    Estado *bloco0 = malloc(sizeof(Estado));
    bloco0->transicoes = NULL;
    bloco0->chamadas = NULL;
    bloco0->estado = 0;
    HASH_ADD_INT(bloco->estadosTransicoes, estado, bloco0);



    TransicaoChamada *bloco0_C1 = malloc(sizeof(TransicaoChamada));
    bloco0_C1->token = "VAR";
    bloco0_C1->submaquina = "declaracoes";
    bloco0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, bloco0->chamadas, bloco0_C1->token, strlen(bloco0_C1->token), bloco0_C1);

    TransicaoChamada *bloco0_C2 = malloc(sizeof(TransicaoChamada));
    bloco0_C2->token = "FUNCTION";
    bloco0_C2->submaquina = "funcoes";
    bloco0_C2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, bloco0->chamadas, bloco0_C2->token, strlen(bloco0_C2->token), bloco0_C2);

    TransicaoChamada *bloco0_C3 = malloc(sizeof(TransicaoChamada));
    bloco0_C3->token = "IF";
    bloco0_C3->submaquina = "comandos";
    bloco0_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco0->chamadas, bloco0_C3->token, strlen(bloco0_C3->token), bloco0_C3);

    TransicaoChamada *bloco0_C4 = malloc(sizeof(TransicaoChamada));
    bloco0_C4->token = "CALL";
    bloco0_C4->submaquina = "comandos";
    bloco0_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco0->chamadas, bloco0_C4->token, strlen(bloco0_C4->token), bloco0_C4);

    TransicaoChamada *bloco0_C5 = malloc(sizeof(TransicaoChamada));
    bloco0_C5->token = "WHILE";
    bloco0_C5->submaquina = "comandos";
    bloco0_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco0->chamadas, bloco0_C5->token, strlen(bloco0_C5->token), bloco0_C5);

    TransicaoChamada *bloco0_C6 = malloc(sizeof(TransicaoChamada));
    bloco0_C6->token = "id";
    bloco0_C6->submaquina = "comandos";
    bloco0_C6->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco0->chamadas, bloco0_C6->token, strlen(bloco0_C6->token), bloco0_C6);

    TransicaoChamada *bloco0_C7 = malloc(sizeof(TransicaoChamada));
    bloco0_C7->token = "INPUT";
    bloco0_C7->submaquina = "comandos";
    bloco0_C7->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco0->chamadas, bloco0_C7->token, strlen(bloco0_C7->token), bloco0_C7);

    TransicaoChamada *bloco0_C8 = malloc(sizeof(TransicaoChamada));
    bloco0_C8->token = "OUTPUT";
    bloco0_C8->submaquina = "comandos";
    bloco0_C8->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco0->chamadas, bloco0_C8->token, strlen(bloco0_C8->token), bloco0_C8);


    Estado *bloco1 = malloc(sizeof(Estado));
    bloco1->transicoes = NULL;
    bloco1->chamadas = NULL;
    bloco1->estado = 1;
    HASH_ADD_INT(bloco->estadosTransicoes, estado, bloco1);



    TransicaoChamada *bloco1_C1 = malloc(sizeof(TransicaoChamada));
    bloco1_C1->token = "FUNCTION";
    bloco1_C1->submaquina = "funcoes";
    bloco1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, bloco1->chamadas, bloco1_C1->token, strlen(bloco1_C1->token), bloco1_C1);

    TransicaoChamada *bloco1_C2 = malloc(sizeof(TransicaoChamada));
    bloco1_C2->token = "IF";
    bloco1_C2->submaquina = "comandos";
    bloco1_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco1->chamadas, bloco1_C2->token, strlen(bloco1_C2->token), bloco1_C2);

    TransicaoChamada *bloco1_C3 = malloc(sizeof(TransicaoChamada));
    bloco1_C3->token = "CALL";
    bloco1_C3->submaquina = "comandos";
    bloco1_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco1->chamadas, bloco1_C3->token, strlen(bloco1_C3->token), bloco1_C3);

    TransicaoChamada *bloco1_C4 = malloc(sizeof(TransicaoChamada));
    bloco1_C4->token = "WHILE";
    bloco1_C4->submaquina = "comandos";
    bloco1_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco1->chamadas, bloco1_C4->token, strlen(bloco1_C4->token), bloco1_C4);

    TransicaoChamada *bloco1_C5 = malloc(sizeof(TransicaoChamada));
    bloco1_C5->token = "id";
    bloco1_C5->submaquina = "comandos";
    bloco1_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco1->chamadas, bloco1_C5->token, strlen(bloco1_C5->token), bloco1_C5);

    TransicaoChamada *bloco1_C6 = malloc(sizeof(TransicaoChamada));
    bloco1_C6->token = "INPUT";
    bloco1_C6->submaquina = "comandos";
    bloco1_C6->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco1->chamadas, bloco1_C6->token, strlen(bloco1_C6->token), bloco1_C6);

    TransicaoChamada *bloco1_C7 = malloc(sizeof(TransicaoChamada));
    bloco1_C7->token = "OUTPUT";
    bloco1_C7->submaquina = "comandos";
    bloco1_C7->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco1->chamadas, bloco1_C7->token, strlen(bloco1_C7->token), bloco1_C7);


    Estado *bloco2 = malloc(sizeof(Estado));
    bloco2->transicoes = NULL;
    bloco2->chamadas = NULL;
    bloco2->estado = 2;
    HASH_ADD_INT(bloco->estadosTransicoes, estado, bloco2);



    TransicaoChamada *bloco2_C1 = malloc(sizeof(TransicaoChamada));
    bloco2_C1->token = "IF";
    bloco2_C1->submaquina = "comandos";
    bloco2_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco2->chamadas, bloco2_C1->token, strlen(bloco2_C1->token), bloco2_C1);

    TransicaoChamada *bloco2_C2 = malloc(sizeof(TransicaoChamada));
    bloco2_C2->token = "CALL";
    bloco2_C2->submaquina = "comandos";
    bloco2_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco2->chamadas, bloco2_C2->token, strlen(bloco2_C2->token), bloco2_C2);

    TransicaoChamada *bloco2_C3 = malloc(sizeof(TransicaoChamada));
    bloco2_C3->token = "WHILE";
    bloco2_C3->submaquina = "comandos";
    bloco2_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco2->chamadas, bloco2_C3->token, strlen(bloco2_C3->token), bloco2_C3);

    TransicaoChamada *bloco2_C4 = malloc(sizeof(TransicaoChamada));
    bloco2_C4->token = "id";
    bloco2_C4->submaquina = "comandos";
    bloco2_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco2->chamadas, bloco2_C4->token, strlen(bloco2_C4->token), bloco2_C4);

    TransicaoChamada *bloco2_C5 = malloc(sizeof(TransicaoChamada));
    bloco2_C5->token = "INPUT";
    bloco2_C5->submaquina = "comandos";
    bloco2_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco2->chamadas, bloco2_C5->token, strlen(bloco2_C5->token), bloco2_C5);

    TransicaoChamada *bloco2_C6 = malloc(sizeof(TransicaoChamada));
    bloco2_C6->token = "OUTPUT";
    bloco2_C6->submaquina = "comandos";
    bloco2_C6->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, bloco2->chamadas, bloco2_C6->token, strlen(bloco2_C6->token), bloco2_C6);



    HASH_ADD_KEYPTR(hh, ape->automatos, bloco->title, strlen(bloco->title), bloco);

    /* declaracoes */

    Automato *declaracoes = malloc(sizeof(Automato));
    declaracoes->estadosTransicoes = NULL;
    declaracoes->title = "declaracoes";
    declaracoes->estado = 0;
    utarray_new(declaracoes->estadosFinais, &ut_int_icd);



    push_tmp = 3; utarray_push_back(declaracoes->estadosFinais, &push_tmp);



    Estado *declaracoes0 = malloc(sizeof(Estado));
    declaracoes0->transicoes = NULL;
    declaracoes0->chamadas = NULL;
    declaracoes0->estado = 0;
    HASH_ADD_INT(declaracoes->estadosTransicoes, estado, declaracoes0);


    Transicao *declaracoes0_T1 = malloc(sizeof(Transicao));
    declaracoes0_T1->token = "VAR";
    declaracoes0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, declaracoes0->transicoes, declaracoes0_T1->token, strlen(declaracoes0_T1->token), declaracoes0_T1);



    Estado *declaracoes1 = malloc(sizeof(Estado));
    declaracoes1->transicoes = NULL;
    declaracoes1->chamadas = NULL;
    declaracoes1->estado = 1;
    HASH_ADD_INT(declaracoes->estadosTransicoes, estado, declaracoes1);



    TransicaoChamada *declaracoes1_C1 = malloc(sizeof(TransicaoChamada));
    declaracoes1_C1->token = "id";
    declaracoes1_C1->submaquina = "id";
    declaracoes1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, declaracoes1->chamadas, declaracoes1_C1->token, strlen(declaracoes1_C1->token), declaracoes1_C1);


    Estado *declaracoes2 = malloc(sizeof(Estado));
    declaracoes2->transicoes = NULL;
    declaracoes2->chamadas = NULL;
    declaracoes2->estado = 2;
    HASH_ADD_INT(declaracoes->estadosTransicoes, estado, declaracoes2);


    Transicao *declaracoes2_T1 = malloc(sizeof(Transicao));
    declaracoes2_T1->token = ",";
    declaracoes2_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, declaracoes2->transicoes, declaracoes2_T1->token, strlen(declaracoes2_T1->token), declaracoes2_T1);

    Transicao *declaracoes2_T2 = malloc(sizeof(Transicao));
    declaracoes2_T2->token = ";";
    declaracoes2_T2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, declaracoes2->transicoes, declaracoes2_T2->token, strlen(declaracoes2_T2->token), declaracoes2_T2);




    HASH_ADD_KEYPTR(hh, ape->automatos, declaracoes->title, strlen(declaracoes->title), declaracoes);

    /* funcoes */

    Automato *funcoes = malloc(sizeof(Automato));
    funcoes->estadosTransicoes = NULL;
    funcoes->title = "funcoes";
    funcoes->estado = 0;
    utarray_new(funcoes->estadosFinais, &ut_int_icd);



    push_tmp = 7; utarray_push_back(funcoes->estadosFinais, &push_tmp);



    Estado *funcoes0 = malloc(sizeof(Estado));
    funcoes0->transicoes = NULL;
    funcoes0->chamadas = NULL;
    funcoes0->estado = 0;
    HASH_ADD_INT(funcoes->estadosTransicoes, estado, funcoes0);


    Transicao *funcoes0_T1 = malloc(sizeof(Transicao));
    funcoes0_T1->token = "FUNCTION";
    funcoes0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, funcoes0->transicoes, funcoes0_T1->token, strlen(funcoes0_T1->token), funcoes0_T1);



    Estado *funcoes1 = malloc(sizeof(Estado));
    funcoes1->transicoes = NULL;
    funcoes1->chamadas = NULL;
    funcoes1->estado = 1;
    HASH_ADD_INT(funcoes->estadosTransicoes, estado, funcoes1);



    TransicaoChamada *funcoes1_C1 = malloc(sizeof(TransicaoChamada));
    funcoes1_C1->token = "id";
    funcoes1_C1->submaquina = "id";
    funcoes1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, funcoes1->chamadas, funcoes1_C1->token, strlen(funcoes1_C1->token), funcoes1_C1);


    Estado *funcoes2 = malloc(sizeof(Estado));
    funcoes2->transicoes = NULL;
    funcoes2->chamadas = NULL;
    funcoes2->estado = 2;
    HASH_ADD_INT(funcoes->estadosTransicoes, estado, funcoes2);


    Transicao *funcoes2_T1 = malloc(sizeof(Transicao));
    funcoes2_T1->token = "BEGIN";
    funcoes2_T1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, funcoes2->transicoes, funcoes2_T1->token, strlen(funcoes2_T1->token), funcoes2_T1);



    Estado *funcoes3 = malloc(sizeof(Estado));
    funcoes3->transicoes = NULL;
    funcoes3->chamadas = NULL;
    funcoes3->estado = 3;
    HASH_ADD_INT(funcoes->estadosTransicoes, estado, funcoes3);



    TransicaoChamada *funcoes3_C1 = malloc(sizeof(TransicaoChamada));
    funcoes3_C1->token = "OUTPUT";
    funcoes3_C1->submaquina = "bloco";
    funcoes3_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, funcoes3->chamadas, funcoes3_C1->token, strlen(funcoes3_C1->token), funcoes3_C1);

    TransicaoChamada *funcoes3_C2 = malloc(sizeof(TransicaoChamada));
    funcoes3_C2->token = "CALL";
    funcoes3_C2->submaquina = "bloco";
    funcoes3_C2->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, funcoes3->chamadas, funcoes3_C2->token, strlen(funcoes3_C2->token), funcoes3_C2);

    TransicaoChamada *funcoes3_C3 = malloc(sizeof(TransicaoChamada));
    funcoes3_C3->token = "WHILE";
    funcoes3_C3->submaquina = "bloco";
    funcoes3_C3->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, funcoes3->chamadas, funcoes3_C3->token, strlen(funcoes3_C3->token), funcoes3_C3);

    TransicaoChamada *funcoes3_C4 = malloc(sizeof(TransicaoChamada));
    funcoes3_C4->token = "VAR";
    funcoes3_C4->submaquina = "bloco";
    funcoes3_C4->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, funcoes3->chamadas, funcoes3_C4->token, strlen(funcoes3_C4->token), funcoes3_C4);

    TransicaoChamada *funcoes3_C5 = malloc(sizeof(TransicaoChamada));
    funcoes3_C5->token = "FUNCTION";
    funcoes3_C5->submaquina = "bloco";
    funcoes3_C5->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, funcoes3->chamadas, funcoes3_C5->token, strlen(funcoes3_C5->token), funcoes3_C5);

    TransicaoChamada *funcoes3_C6 = malloc(sizeof(TransicaoChamada));
    funcoes3_C6->token = "id";
    funcoes3_C6->submaquina = "bloco";
    funcoes3_C6->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, funcoes3->chamadas, funcoes3_C6->token, strlen(funcoes3_C6->token), funcoes3_C6);

    TransicaoChamada *funcoes3_C7 = malloc(sizeof(TransicaoChamada));
    funcoes3_C7->token = "INPUT";
    funcoes3_C7->submaquina = "bloco";
    funcoes3_C7->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, funcoes3->chamadas, funcoes3_C7->token, strlen(funcoes3_C7->token), funcoes3_C7);

    TransicaoChamada *funcoes3_C8 = malloc(sizeof(TransicaoChamada));
    funcoes3_C8->token = "IF";
    funcoes3_C8->submaquina = "bloco";
    funcoes3_C8->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, funcoes3->chamadas, funcoes3_C8->token, strlen(funcoes3_C8->token), funcoes3_C8);


    Estado *funcoes4 = malloc(sizeof(Estado));
    funcoes4->transicoes = NULL;
    funcoes4->chamadas = NULL;
    funcoes4->estado = 4;
    HASH_ADD_INT(funcoes->estadosTransicoes, estado, funcoes4);


    Transicao *funcoes4_T1 = malloc(sizeof(Transicao));
    funcoes4_T1->token = "END";
    funcoes4_T1->estadoResultado = 5;
    HASH_ADD_KEYPTR(hh, funcoes4->transicoes, funcoes4_T1->token, strlen(funcoes4_T1->token), funcoes4_T1);



    Estado *funcoes5 = malloc(sizeof(Estado));
    funcoes5->transicoes = NULL;
    funcoes5->chamadas = NULL;
    funcoes5->estado = 5;
    HASH_ADD_INT(funcoes->estadosTransicoes, estado, funcoes5);


    Transicao *funcoes5_T1 = malloc(sizeof(Transicao));
    funcoes5_T1->token = "FUNCTION";
    funcoes5_T1->estadoResultado = 6;
    HASH_ADD_KEYPTR(hh, funcoes5->transicoes, funcoes5_T1->token, strlen(funcoes5_T1->token), funcoes5_T1);



    Estado *funcoes6 = malloc(sizeof(Estado));
    funcoes6->transicoes = NULL;
    funcoes6->chamadas = NULL;
    funcoes6->estado = 6;
    HASH_ADD_INT(funcoes->estadosTransicoes, estado, funcoes6);


    Transicao *funcoes6_T1 = malloc(sizeof(Transicao));
    funcoes6_T1->token = ";";
    funcoes6_T1->estadoResultado = 7;
    HASH_ADD_KEYPTR(hh, funcoes6->transicoes, funcoes6_T1->token, strlen(funcoes6_T1->token), funcoes6_T1);




    HASH_ADD_KEYPTR(hh, ape->automatos, funcoes->title, strlen(funcoes->title), funcoes);

    /* comandos */

    Automato *comandos = malloc(sizeof(Automato));
    comandos->estadosTransicoes = NULL;
    comandos->title = "comandos";
    comandos->estado = 0;
    utarray_new(comandos->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(comandos->estadosFinais, &push_tmp);



    Estado *comandos0 = malloc(sizeof(Estado));
    comandos0->transicoes = NULL;
    comandos0->chamadas = NULL;
    comandos0->estado = 0;
    HASH_ADD_INT(comandos->estadosTransicoes, estado, comandos0);



    TransicaoChamada *comandos0_C1 = malloc(sizeof(TransicaoChamada));
    comandos0_C1->token = "id";
    comandos0_C1->submaquina = "atribuicao";
    comandos0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos0->chamadas, comandos0_C1->token, strlen(comandos0_C1->token), comandos0_C1);

    TransicaoChamada *comandos0_C2 = malloc(sizeof(TransicaoChamada));
    comandos0_C2->token = "IF";
    comandos0_C2->submaquina = "condicional";
    comandos0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos0->chamadas, comandos0_C2->token, strlen(comandos0_C2->token), comandos0_C2);

    TransicaoChamada *comandos0_C3 = malloc(sizeof(TransicaoChamada));
    comandos0_C3->token = "INPUT";
    comandos0_C3->submaquina = "entrada";
    comandos0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos0->chamadas, comandos0_C3->token, strlen(comandos0_C3->token), comandos0_C3);

    TransicaoChamada *comandos0_C4 = malloc(sizeof(TransicaoChamada));
    comandos0_C4->token = "OUTPUT";
    comandos0_C4->submaquina = "saida";
    comandos0_C4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos0->chamadas, comandos0_C4->token, strlen(comandos0_C4->token), comandos0_C4);

    TransicaoChamada *comandos0_C5 = malloc(sizeof(TransicaoChamada));
    comandos0_C5->token = "WHILE";
    comandos0_C5->submaquina = "iterativo";
    comandos0_C5->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos0->chamadas, comandos0_C5->token, strlen(comandos0_C5->token), comandos0_C5);

    TransicaoChamada *comandos0_C6 = malloc(sizeof(TransicaoChamada));
    comandos0_C6->token = "CALL";
    comandos0_C6->submaquina = "chamada";
    comandos0_C6->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos0->chamadas, comandos0_C6->token, strlen(comandos0_C6->token), comandos0_C6);


    Estado *comandos1 = malloc(sizeof(Estado));
    comandos1->transicoes = NULL;
    comandos1->chamadas = NULL;
    comandos1->estado = 1;
    HASH_ADD_INT(comandos->estadosTransicoes, estado, comandos1);


    Transicao *comandos1_T1 = malloc(sizeof(Transicao));
    comandos1_T1->token = ";";
    comandos1_T1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, comandos1->transicoes, comandos1_T1->token, strlen(comandos1_T1->token), comandos1_T1);



    Estado *comandos2 = malloc(sizeof(Estado));
    comandos2->transicoes = NULL;
    comandos2->chamadas = NULL;
    comandos2->estado = 2;
    HASH_ADD_INT(comandos->estadosTransicoes, estado, comandos2);



    TransicaoChamada *comandos2_C1 = malloc(sizeof(TransicaoChamada));
    comandos2_C1->token = "IF";
    comandos2_C1->submaquina = "comandos";
    comandos2_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos2->chamadas, comandos2_C1->token, strlen(comandos2_C1->token), comandos2_C1);

    TransicaoChamada *comandos2_C2 = malloc(sizeof(TransicaoChamada));
    comandos2_C2->token = "CALL";
    comandos2_C2->submaquina = "comandos";
    comandos2_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos2->chamadas, comandos2_C2->token, strlen(comandos2_C2->token), comandos2_C2);

    TransicaoChamada *comandos2_C3 = malloc(sizeof(TransicaoChamada));
    comandos2_C3->token = "WHILE";
    comandos2_C3->submaquina = "comandos";
    comandos2_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos2->chamadas, comandos2_C3->token, strlen(comandos2_C3->token), comandos2_C3);

    TransicaoChamada *comandos2_C4 = malloc(sizeof(TransicaoChamada));
    comandos2_C4->token = "id";
    comandos2_C4->submaquina = "comandos";
    comandos2_C4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos2->chamadas, comandos2_C4->token, strlen(comandos2_C4->token), comandos2_C4);

    TransicaoChamada *comandos2_C5 = malloc(sizeof(TransicaoChamada));
    comandos2_C5->token = "INPUT";
    comandos2_C5->submaquina = "comandos";
    comandos2_C5->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos2->chamadas, comandos2_C5->token, strlen(comandos2_C5->token), comandos2_C5);

    TransicaoChamada *comandos2_C6 = malloc(sizeof(TransicaoChamada));
    comandos2_C6->token = "OUTPUT";
    comandos2_C6->submaquina = "comandos";
    comandos2_C6->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comandos2->chamadas, comandos2_C6->token, strlen(comandos2_C6->token), comandos2_C6);



    HASH_ADD_KEYPTR(hh, ape->automatos, comandos->title, strlen(comandos->title), comandos);

    /* booleano */

    Automato *booleano = malloc(sizeof(Automato));
    booleano->estadosTransicoes = NULL;
    booleano->title = "booleano";
    booleano->estado = 0;
    utarray_new(booleano->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(booleano->estadosFinais, &push_tmp);



    Estado *booleano0 = malloc(sizeof(Estado));
    booleano0->transicoes = NULL;
    booleano0->chamadas = NULL;
    booleano0->estado = 0;
    HASH_ADD_INT(booleano->estadosTransicoes, estado, booleano0);


    Transicao *booleano0_T1 = malloc(sizeof(Transicao));
    booleano0_T1->token = "#t";
    booleano0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, booleano0->transicoes, booleano0_T1->token, strlen(booleano0_T1->token), booleano0_T1);

    Transicao *booleano0_T2 = malloc(sizeof(Transicao));
    booleano0_T2->token = "#f";
    booleano0_T2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, booleano0->transicoes, booleano0_T2->token, strlen(booleano0_T2->token), booleano0_T2);




    HASH_ADD_KEYPTR(hh, ape->automatos, booleano->title, strlen(booleano->title), booleano);

    /* operador */

    Automato *operador = malloc(sizeof(Automato));
    operador->estadosTransicoes = NULL;
    operador->title = "operador";
    operador->estado = 0;
    utarray_new(operador->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(operador->estadosFinais, &push_tmp);



    Estado *operador0 = malloc(sizeof(Estado));
    operador0->transicoes = NULL;
    operador0->chamadas = NULL;
    operador0->estado = 0;
    HASH_ADD_INT(operador->estadosTransicoes, estado, operador0);



    TransicaoChamada *operador0_C1 = malloc(sizeof(TransicaoChamada));
    operador0_C1->token = "AND";
    operador0_C1->submaquina = "operador_booleano";
    operador0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C1->token, strlen(operador0_C1->token), operador0_C1);

    TransicaoChamada *operador0_C2 = malloc(sizeof(TransicaoChamada));
    operador0_C2->token = "OR";
    operador0_C2->submaquina = "operador_booleano";
    operador0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C2->token, strlen(operador0_C2->token), operador0_C2);

    TransicaoChamada *operador0_C3 = malloc(sizeof(TransicaoChamada));
    operador0_C3->token = "<=";
    operador0_C3->submaquina = "operador_comparacao";
    operador0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C3->token, strlen(operador0_C3->token), operador0_C3);

    TransicaoChamada *operador0_C4 = malloc(sizeof(TransicaoChamada));
    operador0_C4->token = "==";
    operador0_C4->submaquina = "operador_comparacao";
    operador0_C4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C4->token, strlen(operador0_C4->token), operador0_C4);

    TransicaoChamada *operador0_C5 = malloc(sizeof(TransicaoChamada));
    operador0_C5->token = "<";
    operador0_C5->submaquina = "operador_comparacao";
    operador0_C5->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C5->token, strlen(operador0_C5->token), operador0_C5);

    TransicaoChamada *operador0_C6 = malloc(sizeof(TransicaoChamada));
    operador0_C6->token = ">=";
    operador0_C6->submaquina = "operador_comparacao";
    operador0_C6->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C6->token, strlen(operador0_C6->token), operador0_C6);

    TransicaoChamada *operador0_C7 = malloc(sizeof(TransicaoChamada));
    operador0_C7->token = ">";
    operador0_C7->submaquina = "operador_comparacao";
    operador0_C7->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C7->token, strlen(operador0_C7->token), operador0_C7);

    TransicaoChamada *operador0_C8 = malloc(sizeof(TransicaoChamada));
    operador0_C8->token = "!=";
    operador0_C8->submaquina = "operador_comparacao";
    operador0_C8->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C8->token, strlen(operador0_C8->token), operador0_C8);

    TransicaoChamada *operador0_C9 = malloc(sizeof(TransicaoChamada));
    operador0_C9->token = "-";
    operador0_C9->submaquina = "operador_aritmetico";
    operador0_C9->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C9->token, strlen(operador0_C9->token), operador0_C9);

    TransicaoChamada *operador0_C10 = malloc(sizeof(TransicaoChamada));
    operador0_C10->token = "/";
    operador0_C10->submaquina = "operador_aritmetico";
    operador0_C10->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C10->token, strlen(operador0_C10->token), operador0_C10);

    TransicaoChamada *operador0_C11 = malloc(sizeof(TransicaoChamada));
    operador0_C11->token = "*";
    operador0_C11->submaquina = "operador_aritmetico";
    operador0_C11->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C11->token, strlen(operador0_C11->token), operador0_C11);

    TransicaoChamada *operador0_C12 = malloc(sizeof(TransicaoChamada));
    operador0_C12->token = "%";
    operador0_C12->submaquina = "operador_aritmetico";
    operador0_C12->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C12->token, strlen(operador0_C12->token), operador0_C12);

    TransicaoChamada *operador0_C13 = malloc(sizeof(TransicaoChamada));
    operador0_C13->token = "+";
    operador0_C13->submaquina = "operador_aritmetico";
    operador0_C13->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador0->chamadas, operador0_C13->token, strlen(operador0_C13->token), operador0_C13);



    HASH_ADD_KEYPTR(hh, ape->automatos, operador->title, strlen(operador->title), operador);

    /* operador_booleano */

    Automato *operador_booleano = malloc(sizeof(Automato));
    operador_booleano->estadosTransicoes = NULL;
    operador_booleano->title = "operador_booleano";
    operador_booleano->estado = 0;
    utarray_new(operador_booleano->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(operador_booleano->estadosFinais, &push_tmp);



    Estado *operador_booleano0 = malloc(sizeof(Estado));
    operador_booleano0->transicoes = NULL;
    operador_booleano0->chamadas = NULL;
    operador_booleano0->estado = 0;
    HASH_ADD_INT(operador_booleano->estadosTransicoes, estado, operador_booleano0);


    Transicao *operador_booleano0_T1 = malloc(sizeof(Transicao));
    operador_booleano0_T1->token = "OR";
    operador_booleano0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_booleano0->transicoes, operador_booleano0_T1->token, strlen(operador_booleano0_T1->token), operador_booleano0_T1);

    Transicao *operador_booleano0_T2 = malloc(sizeof(Transicao));
    operador_booleano0_T2->token = "AND";
    operador_booleano0_T2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_booleano0->transicoes, operador_booleano0_T2->token, strlen(operador_booleano0_T2->token), operador_booleano0_T2);




    HASH_ADD_KEYPTR(hh, ape->automatos, operador_booleano->title, strlen(operador_booleano->title), operador_booleano);

    /* operador_comparacao */

    Automato *operador_comparacao = malloc(sizeof(Automato));
    operador_comparacao->estadosTransicoes = NULL;
    operador_comparacao->title = "operador_comparacao";
    operador_comparacao->estado = 0;
    utarray_new(operador_comparacao->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(operador_comparacao->estadosFinais, &push_tmp);



    Estado *operador_comparacao0 = malloc(sizeof(Estado));
    operador_comparacao0->transicoes = NULL;
    operador_comparacao0->chamadas = NULL;
    operador_comparacao0->estado = 0;
    HASH_ADD_INT(operador_comparacao->estadosTransicoes, estado, operador_comparacao0);


    Transicao *operador_comparacao0_T1 = malloc(sizeof(Transicao));
    operador_comparacao0_T1->token = ">";
    operador_comparacao0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_comparacao0->transicoes, operador_comparacao0_T1->token, strlen(operador_comparacao0_T1->token), operador_comparacao0_T1);

    Transicao *operador_comparacao0_T2 = malloc(sizeof(Transicao));
    operador_comparacao0_T2->token = ">=";
    operador_comparacao0_T2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_comparacao0->transicoes, operador_comparacao0_T2->token, strlen(operador_comparacao0_T2->token), operador_comparacao0_T2);

    Transicao *operador_comparacao0_T3 = malloc(sizeof(Transicao));
    operador_comparacao0_T3->token = "<";
    operador_comparacao0_T3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_comparacao0->transicoes, operador_comparacao0_T3->token, strlen(operador_comparacao0_T3->token), operador_comparacao0_T3);

    Transicao *operador_comparacao0_T4 = malloc(sizeof(Transicao));
    operador_comparacao0_T4->token = "<=";
    operador_comparacao0_T4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_comparacao0->transicoes, operador_comparacao0_T4->token, strlen(operador_comparacao0_T4->token), operador_comparacao0_T4);

    Transicao *operador_comparacao0_T5 = malloc(sizeof(Transicao));
    operador_comparacao0_T5->token = "==";
    operador_comparacao0_T5->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_comparacao0->transicoes, operador_comparacao0_T5->token, strlen(operador_comparacao0_T5->token), operador_comparacao0_T5);

    Transicao *operador_comparacao0_T6 = malloc(sizeof(Transicao));
    operador_comparacao0_T6->token = "!=";
    operador_comparacao0_T6->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_comparacao0->transicoes, operador_comparacao0_T6->token, strlen(operador_comparacao0_T6->token), operador_comparacao0_T6);




    HASH_ADD_KEYPTR(hh, ape->automatos, operador_comparacao->title, strlen(operador_comparacao->title), operador_comparacao);

    /* operador_aritmetico */

    Automato *operador_aritmetico = malloc(sizeof(Automato));
    operador_aritmetico->estadosTransicoes = NULL;
    operador_aritmetico->title = "operador_aritmetico";
    operador_aritmetico->estado = 0;
    utarray_new(operador_aritmetico->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(operador_aritmetico->estadosFinais, &push_tmp);



    Estado *operador_aritmetico0 = malloc(sizeof(Estado));
    operador_aritmetico0->transicoes = NULL;
    operador_aritmetico0->chamadas = NULL;
    operador_aritmetico0->estado = 0;
    HASH_ADD_INT(operador_aritmetico->estadosTransicoes, estado, operador_aritmetico0);


    Transicao *operador_aritmetico0_T1 = malloc(sizeof(Transicao));
    operador_aritmetico0_T1->token = "+";
    operador_aritmetico0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_aritmetico0->transicoes, operador_aritmetico0_T1->token, strlen(operador_aritmetico0_T1->token), operador_aritmetico0_T1);

    Transicao *operador_aritmetico0_T2 = malloc(sizeof(Transicao));
    operador_aritmetico0_T2->token = "-";
    operador_aritmetico0_T2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_aritmetico0->transicoes, operador_aritmetico0_T2->token, strlen(operador_aritmetico0_T2->token), operador_aritmetico0_T2);

    Transicao *operador_aritmetico0_T3 = malloc(sizeof(Transicao));
    operador_aritmetico0_T3->token = "/";
    operador_aritmetico0_T3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_aritmetico0->transicoes, operador_aritmetico0_T3->token, strlen(operador_aritmetico0_T3->token), operador_aritmetico0_T3);

    Transicao *operador_aritmetico0_T4 = malloc(sizeof(Transicao));
    operador_aritmetico0_T4->token = "%";
    operador_aritmetico0_T4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_aritmetico0->transicoes, operador_aritmetico0_T4->token, strlen(operador_aritmetico0_T4->token), operador_aritmetico0_T4);

    Transicao *operador_aritmetico0_T5 = malloc(sizeof(Transicao));
    operador_aritmetico0_T5->token = "*";
    operador_aritmetico0_T5->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, operador_aritmetico0->transicoes, operador_aritmetico0_T5->token, strlen(operador_aritmetico0_T5->token), operador_aritmetico0_T5);




    HASH_ADD_KEYPTR(hh, ape->automatos, operador_aritmetico->title, strlen(operador_aritmetico->title), operador_aritmetico);

    /* expressao */

    Automato *expressao = malloc(sizeof(Automato));
    expressao->estadosTransicoes = NULL;
    expressao->title = "expressao";
    expressao->estado = 0;
    utarray_new(expressao->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(expressao->estadosFinais, &push_tmp);



    Estado *expressao0 = malloc(sizeof(Estado));
    expressao0->transicoes = NULL;
    expressao0->chamadas = NULL;
    expressao0->estado = 0;
    HASH_ADD_INT(expressao->estadosTransicoes, estado, expressao0);



    TransicaoChamada *expressao0_C1 = malloc(sizeof(TransicaoChamada));
    expressao0_C1->token = "#f";
    expressao0_C1->submaquina = "expressao_";
    expressao0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao0->chamadas, expressao0_C1->token, strlen(expressao0_C1->token), expressao0_C1);

    TransicaoChamada *expressao0_C2 = malloc(sizeof(TransicaoChamada));
    expressao0_C2->token = "#t";
    expressao0_C2->submaquina = "expressao_";
    expressao0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao0->chamadas, expressao0_C2->token, strlen(expressao0_C2->token), expressao0_C2);

    TransicaoChamada *expressao0_C3 = malloc(sizeof(TransicaoChamada));
    expressao0_C3->token = "(";
    expressao0_C3->submaquina = "expressao_";
    expressao0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao0->chamadas, expressao0_C3->token, strlen(expressao0_C3->token), expressao0_C3);

    TransicaoChamada *expressao0_C4 = malloc(sizeof(TransicaoChamada));
    expressao0_C4->token = "numero";
    expressao0_C4->submaquina = "expressao_";
    expressao0_C4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao0->chamadas, expressao0_C4->token, strlen(expressao0_C4->token), expressao0_C4);

    TransicaoChamada *expressao0_C5 = malloc(sizeof(TransicaoChamada));
    expressao0_C5->token = "id";
    expressao0_C5->submaquina = "expressao_";
    expressao0_C5->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao0->chamadas, expressao0_C5->token, strlen(expressao0_C5->token), expressao0_C5);


    Estado *expressao1 = malloc(sizeof(Estado));
    expressao1->transicoes = NULL;
    expressao1->chamadas = NULL;
    expressao1->estado = 1;
    HASH_ADD_INT(expressao->estadosTransicoes, estado, expressao1);



    TransicaoChamada *expressao1_C1 = malloc(sizeof(TransicaoChamada));
    expressao1_C1->token = "-";
    expressao1_C1->submaquina = "operador";
    expressao1_C1->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C1->token, strlen(expressao1_C1->token), expressao1_C1);

    TransicaoChamada *expressao1_C2 = malloc(sizeof(TransicaoChamada));
    expressao1_C2->token = "+";
    expressao1_C2->submaquina = "operador";
    expressao1_C2->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C2->token, strlen(expressao1_C2->token), expressao1_C2);

    TransicaoChamada *expressao1_C3 = malloc(sizeof(TransicaoChamada));
    expressao1_C3->token = "/";
    expressao1_C3->submaquina = "operador";
    expressao1_C3->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C3->token, strlen(expressao1_C3->token), expressao1_C3);

    TransicaoChamada *expressao1_C4 = malloc(sizeof(TransicaoChamada));
    expressao1_C4->token = "*";
    expressao1_C4->submaquina = "operador";
    expressao1_C4->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C4->token, strlen(expressao1_C4->token), expressao1_C4);

    TransicaoChamada *expressao1_C5 = malloc(sizeof(TransicaoChamada));
    expressao1_C5->token = "%";
    expressao1_C5->submaquina = "operador";
    expressao1_C5->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C5->token, strlen(expressao1_C5->token), expressao1_C5);

    TransicaoChamada *expressao1_C6 = malloc(sizeof(TransicaoChamada));
    expressao1_C6->token = "<=";
    expressao1_C6->submaquina = "operador";
    expressao1_C6->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C6->token, strlen(expressao1_C6->token), expressao1_C6);

    TransicaoChamada *expressao1_C7 = malloc(sizeof(TransicaoChamada));
    expressao1_C7->token = "==";
    expressao1_C7->submaquina = "operador";
    expressao1_C7->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C7->token, strlen(expressao1_C7->token), expressao1_C7);

    TransicaoChamada *expressao1_C8 = malloc(sizeof(TransicaoChamada));
    expressao1_C8->token = "<";
    expressao1_C8->submaquina = "operador";
    expressao1_C8->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C8->token, strlen(expressao1_C8->token), expressao1_C8);

    TransicaoChamada *expressao1_C9 = malloc(sizeof(TransicaoChamada));
    expressao1_C9->token = "AND";
    expressao1_C9->submaquina = "operador";
    expressao1_C9->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C9->token, strlen(expressao1_C9->token), expressao1_C9);

    TransicaoChamada *expressao1_C10 = malloc(sizeof(TransicaoChamada));
    expressao1_C10->token = ">=";
    expressao1_C10->submaquina = "operador";
    expressao1_C10->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C10->token, strlen(expressao1_C10->token), expressao1_C10);

    TransicaoChamada *expressao1_C11 = malloc(sizeof(TransicaoChamada));
    expressao1_C11->token = ">";
    expressao1_C11->submaquina = "operador";
    expressao1_C11->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C11->token, strlen(expressao1_C11->token), expressao1_C11);

    TransicaoChamada *expressao1_C12 = malloc(sizeof(TransicaoChamada));
    expressao1_C12->token = "!=";
    expressao1_C12->submaquina = "operador";
    expressao1_C12->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C12->token, strlen(expressao1_C12->token), expressao1_C12);

    TransicaoChamada *expressao1_C13 = malloc(sizeof(TransicaoChamada));
    expressao1_C13->token = "OR";
    expressao1_C13->submaquina = "operador";
    expressao1_C13->estadoResultado = 0;
    HASH_ADD_KEYPTR(hh, expressao1->chamadas, expressao1_C13->token, strlen(expressao1_C13->token), expressao1_C13);



    HASH_ADD_KEYPTR(hh, ape->automatos, expressao->title, strlen(expressao->title), expressao);

    /* expressao_ */

    Automato *expressao_ = malloc(sizeof(Automato));
    expressao_->estadosTransicoes = NULL;
    expressao_->title = "expressao_";
    expressao_->estado = 0;
    utarray_new(expressao_->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(expressao_->estadosFinais, &push_tmp);



    Estado *expressao_0 = malloc(sizeof(Estado));
    expressao_0->transicoes = NULL;
    expressao_0->chamadas = NULL;
    expressao_0->estado = 0;
    HASH_ADD_INT(expressao_->estadosTransicoes, estado, expressao_0);


    Transicao *expressao_0_T1 = malloc(sizeof(Transicao));
    expressao_0_T1->token = "(";
    expressao_0_T1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, expressao_0->transicoes, expressao_0_T1->token, strlen(expressao_0_T1->token), expressao_0_T1);


    TransicaoChamada *expressao_0_C1 = malloc(sizeof(TransicaoChamada));
    expressao_0_C1->token = "numero";
    expressao_0_C1->submaquina = "numero";
    expressao_0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao_0->chamadas, expressao_0_C1->token, strlen(expressao_0_C1->token), expressao_0_C1);

    TransicaoChamada *expressao_0_C2 = malloc(sizeof(TransicaoChamada));
    expressao_0_C2->token = "id";
    expressao_0_C2->submaquina = "id";
    expressao_0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao_0->chamadas, expressao_0_C2->token, strlen(expressao_0_C2->token), expressao_0_C2);

    TransicaoChamada *expressao_0_C3 = malloc(sizeof(TransicaoChamada));
    expressao_0_C3->token = "#t";
    expressao_0_C3->submaquina = "booleano";
    expressao_0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao_0->chamadas, expressao_0_C3->token, strlen(expressao_0_C3->token), expressao_0_C3);

    TransicaoChamada *expressao_0_C4 = malloc(sizeof(TransicaoChamada));
    expressao_0_C4->token = "#f";
    expressao_0_C4->submaquina = "booleano";
    expressao_0_C4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao_0->chamadas, expressao_0_C4->token, strlen(expressao_0_C4->token), expressao_0_C4);


    Estado *expressao_2 = malloc(sizeof(Estado));
    expressao_2->transicoes = NULL;
    expressao_2->chamadas = NULL;
    expressao_2->estado = 2;
    HASH_ADD_INT(expressao_->estadosTransicoes, estado, expressao_2);



    TransicaoChamada *expressao_2_C1 = malloc(sizeof(TransicaoChamada));
    expressao_2_C1->token = "(";
    expressao_2_C1->submaquina = "expressao";
    expressao_2_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, expressao_2->chamadas, expressao_2_C1->token, strlen(expressao_2_C1->token), expressao_2_C1);

    TransicaoChamada *expressao_2_C2 = malloc(sizeof(TransicaoChamada));
    expressao_2_C2->token = "id";
    expressao_2_C2->submaquina = "expressao";
    expressao_2_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, expressao_2->chamadas, expressao_2_C2->token, strlen(expressao_2_C2->token), expressao_2_C2);

    TransicaoChamada *expressao_2_C3 = malloc(sizeof(TransicaoChamada));
    expressao_2_C3->token = "#f";
    expressao_2_C3->submaquina = "expressao";
    expressao_2_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, expressao_2->chamadas, expressao_2_C3->token, strlen(expressao_2_C3->token), expressao_2_C3);

    TransicaoChamada *expressao_2_C4 = malloc(sizeof(TransicaoChamada));
    expressao_2_C4->token = "numero";
    expressao_2_C4->submaquina = "expressao";
    expressao_2_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, expressao_2->chamadas, expressao_2_C4->token, strlen(expressao_2_C4->token), expressao_2_C4);

    TransicaoChamada *expressao_2_C5 = malloc(sizeof(TransicaoChamada));
    expressao_2_C5->token = "#t";
    expressao_2_C5->submaquina = "expressao";
    expressao_2_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, expressao_2->chamadas, expressao_2_C5->token, strlen(expressao_2_C5->token), expressao_2_C5);


    Estado *expressao_3 = malloc(sizeof(Estado));
    expressao_3->transicoes = NULL;
    expressao_3->chamadas = NULL;
    expressao_3->estado = 3;
    HASH_ADD_INT(expressao_->estadosTransicoes, estado, expressao_3);


    Transicao *expressao_3_T1 = malloc(sizeof(Transicao));
    expressao_3_T1->token = ")";
    expressao_3_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao_3->transicoes, expressao_3_T1->token, strlen(expressao_3_T1->token), expressao_3_T1);




    HASH_ADD_KEYPTR(hh, ape->automatos, expressao_->title, strlen(expressao_->title), expressao_);

    /* chamada */

    Automato *chamada = malloc(sizeof(Automato));
    chamada->estadosTransicoes = NULL;
    chamada->title = "chamada";
    chamada->estado = 0;
    utarray_new(chamada->estadosFinais, &ut_int_icd);



    push_tmp = 3; utarray_push_back(chamada->estadosFinais, &push_tmp);



    Estado *chamada0 = malloc(sizeof(Estado));
    chamada0->transicoes = NULL;
    chamada0->chamadas = NULL;
    chamada0->estado = 0;
    HASH_ADD_INT(chamada->estadosTransicoes, estado, chamada0);


    Transicao *chamada0_T1 = malloc(sizeof(Transicao));
    chamada0_T1->token = "CALL";
    chamada0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, chamada0->transicoes, chamada0_T1->token, strlen(chamada0_T1->token), chamada0_T1);



    Estado *chamada1 = malloc(sizeof(Estado));
    chamada1->transicoes = NULL;
    chamada1->chamadas = NULL;
    chamada1->estado = 1;
    HASH_ADD_INT(chamada->estadosTransicoes, estado, chamada1);



    TransicaoChamada *chamada1_C1 = malloc(sizeof(TransicaoChamada));
    chamada1_C1->token = "id";
    chamada1_C1->submaquina = "id";
    chamada1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, chamada1->chamadas, chamada1_C1->token, strlen(chamada1_C1->token), chamada1_C1);


    Estado *chamada2 = malloc(sizeof(Estado));
    chamada2->transicoes = NULL;
    chamada2->chamadas = NULL;
    chamada2->estado = 2;
    HASH_ADD_INT(chamada->estadosTransicoes, estado, chamada2);


    Transicao *chamada2_T1 = malloc(sizeof(Transicao));
    chamada2_T1->token = ";";
    chamada2_T1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, chamada2->transicoes, chamada2_T1->token, strlen(chamada2_T1->token), chamada2_T1);




    HASH_ADD_KEYPTR(hh, ape->automatos, chamada->title, strlen(chamada->title), chamada);

    /* atribuicao */

    Automato *atribuicao = malloc(sizeof(Automato));
    atribuicao->estadosTransicoes = NULL;
    atribuicao->title = "atribuicao";
    atribuicao->estado = 0;
    utarray_new(atribuicao->estadosFinais, &ut_int_icd);



    push_tmp = 4; utarray_push_back(atribuicao->estadosFinais, &push_tmp);



    Estado *atribuicao0 = malloc(sizeof(Estado));
    atribuicao0->transicoes = NULL;
    atribuicao0->chamadas = NULL;
    atribuicao0->estado = 0;
    HASH_ADD_INT(atribuicao->estadosTransicoes, estado, atribuicao0);



    TransicaoChamada *atribuicao0_C1 = malloc(sizeof(TransicaoChamada));
    atribuicao0_C1->token = "id";
    atribuicao0_C1->submaquina = "id";
    atribuicao0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, atribuicao0->chamadas, atribuicao0_C1->token, strlen(atribuicao0_C1->token), atribuicao0_C1);


    Estado *atribuicao1 = malloc(sizeof(Estado));
    atribuicao1->transicoes = NULL;
    atribuicao1->chamadas = NULL;
    atribuicao1->estado = 1;
    HASH_ADD_INT(atribuicao->estadosTransicoes, estado, atribuicao1);


    Transicao *atribuicao1_T1 = malloc(sizeof(Transicao));
    atribuicao1_T1->token = ":=";
    atribuicao1_T1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, atribuicao1->transicoes, atribuicao1_T1->token, strlen(atribuicao1_T1->token), atribuicao1_T1);



    Estado *atribuicao2 = malloc(sizeof(Estado));
    atribuicao2->transicoes = NULL;
    atribuicao2->chamadas = NULL;
    atribuicao2->estado = 2;
    HASH_ADD_INT(atribuicao->estadosTransicoes, estado, atribuicao2);



    TransicaoChamada *atribuicao2_C1 = malloc(sizeof(TransicaoChamada));
    atribuicao2_C1->token = "(";
    atribuicao2_C1->submaquina = "expressao";
    atribuicao2_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, atribuicao2->chamadas, atribuicao2_C1->token, strlen(atribuicao2_C1->token), atribuicao2_C1);

    TransicaoChamada *atribuicao2_C2 = malloc(sizeof(TransicaoChamada));
    atribuicao2_C2->token = "id";
    atribuicao2_C2->submaquina = "expressao";
    atribuicao2_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, atribuicao2->chamadas, atribuicao2_C2->token, strlen(atribuicao2_C2->token), atribuicao2_C2);

    TransicaoChamada *atribuicao2_C3 = malloc(sizeof(TransicaoChamada));
    atribuicao2_C3->token = "#f";
    atribuicao2_C3->submaquina = "expressao";
    atribuicao2_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, atribuicao2->chamadas, atribuicao2_C3->token, strlen(atribuicao2_C3->token), atribuicao2_C3);

    TransicaoChamada *atribuicao2_C4 = malloc(sizeof(TransicaoChamada));
    atribuicao2_C4->token = "numero";
    atribuicao2_C4->submaquina = "expressao";
    atribuicao2_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, atribuicao2->chamadas, atribuicao2_C4->token, strlen(atribuicao2_C4->token), atribuicao2_C4);

    TransicaoChamada *atribuicao2_C5 = malloc(sizeof(TransicaoChamada));
    atribuicao2_C5->token = "#t";
    atribuicao2_C5->submaquina = "expressao";
    atribuicao2_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, atribuicao2->chamadas, atribuicao2_C5->token, strlen(atribuicao2_C5->token), atribuicao2_C5);


    Estado *atribuicao3 = malloc(sizeof(Estado));
    atribuicao3->transicoes = NULL;
    atribuicao3->chamadas = NULL;
    atribuicao3->estado = 3;
    HASH_ADD_INT(atribuicao->estadosTransicoes, estado, atribuicao3);


    Transicao *atribuicao3_T1 = malloc(sizeof(Transicao));
    atribuicao3_T1->token = ";";
    atribuicao3_T1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, atribuicao3->transicoes, atribuicao3_T1->token, strlen(atribuicao3_T1->token), atribuicao3_T1);




    HASH_ADD_KEYPTR(hh, ape->automatos, atribuicao->title, strlen(atribuicao->title), atribuicao);

    /* condicional */

    Automato *condicional = malloc(sizeof(Automato));
    condicional->estadosTransicoes = NULL;
    condicional->title = "condicional";
    condicional->estado = 0;
    utarray_new(condicional->estadosFinais, &ut_int_icd);



    push_tmp = 7; utarray_push_back(condicional->estadosFinais, &push_tmp);



    Estado *condicional0 = malloc(sizeof(Estado));
    condicional0->transicoes = NULL;
    condicional0->chamadas = NULL;
    condicional0->estado = 0;
    HASH_ADD_INT(condicional->estadosTransicoes, estado, condicional0);


    Transicao *condicional0_T1 = malloc(sizeof(Transicao));
    condicional0_T1->token = "IF";
    condicional0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, condicional0->transicoes, condicional0_T1->token, strlen(condicional0_T1->token), condicional0_T1);



    Estado *condicional1 = malloc(sizeof(Estado));
    condicional1->transicoes = NULL;
    condicional1->chamadas = NULL;
    condicional1->estado = 1;
    HASH_ADD_INT(condicional->estadosTransicoes, estado, condicional1);



    TransicaoChamada *condicional1_C1 = malloc(sizeof(TransicaoChamada));
    condicional1_C1->token = "(";
    condicional1_C1->submaquina = "expressao";
    condicional1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, condicional1->chamadas, condicional1_C1->token, strlen(condicional1_C1->token), condicional1_C1);

    TransicaoChamada *condicional1_C2 = malloc(sizeof(TransicaoChamada));
    condicional1_C2->token = "id";
    condicional1_C2->submaquina = "expressao";
    condicional1_C2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, condicional1->chamadas, condicional1_C2->token, strlen(condicional1_C2->token), condicional1_C2);

    TransicaoChamada *condicional1_C3 = malloc(sizeof(TransicaoChamada));
    condicional1_C3->token = "#f";
    condicional1_C3->submaquina = "expressao";
    condicional1_C3->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, condicional1->chamadas, condicional1_C3->token, strlen(condicional1_C3->token), condicional1_C3);

    TransicaoChamada *condicional1_C4 = malloc(sizeof(TransicaoChamada));
    condicional1_C4->token = "numero";
    condicional1_C4->submaquina = "expressao";
    condicional1_C4->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, condicional1->chamadas, condicional1_C4->token, strlen(condicional1_C4->token), condicional1_C4);

    TransicaoChamada *condicional1_C5 = malloc(sizeof(TransicaoChamada));
    condicional1_C5->token = "#t";
    condicional1_C5->submaquina = "expressao";
    condicional1_C5->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, condicional1->chamadas, condicional1_C5->token, strlen(condicional1_C5->token), condicional1_C5);


    Estado *condicional2 = malloc(sizeof(Estado));
    condicional2->transicoes = NULL;
    condicional2->chamadas = NULL;
    condicional2->estado = 2;
    HASH_ADD_INT(condicional->estadosTransicoes, estado, condicional2);


    Transicao *condicional2_T1 = malloc(sizeof(Transicao));
    condicional2_T1->token = "THEN";
    condicional2_T1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, condicional2->transicoes, condicional2_T1->token, strlen(condicional2_T1->token), condicional2_T1);



    Estado *condicional3 = malloc(sizeof(Estado));
    condicional3->transicoes = NULL;
    condicional3->chamadas = NULL;
    condicional3->estado = 3;
    HASH_ADD_INT(condicional->estadosTransicoes, estado, condicional3);



    TransicaoChamada *condicional3_C1 = malloc(sizeof(TransicaoChamada));
    condicional3_C1->token = "IF";
    condicional3_C1->submaquina = "comandos";
    condicional3_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, condicional3->chamadas, condicional3_C1->token, strlen(condicional3_C1->token), condicional3_C1);

    TransicaoChamada *condicional3_C2 = malloc(sizeof(TransicaoChamada));
    condicional3_C2->token = "CALL";
    condicional3_C2->submaquina = "comandos";
    condicional3_C2->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, condicional3->chamadas, condicional3_C2->token, strlen(condicional3_C2->token), condicional3_C2);

    TransicaoChamada *condicional3_C3 = malloc(sizeof(TransicaoChamada));
    condicional3_C3->token = "WHILE";
    condicional3_C3->submaquina = "comandos";
    condicional3_C3->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, condicional3->chamadas, condicional3_C3->token, strlen(condicional3_C3->token), condicional3_C3);

    TransicaoChamada *condicional3_C4 = malloc(sizeof(TransicaoChamada));
    condicional3_C4->token = "id";
    condicional3_C4->submaquina = "comandos";
    condicional3_C4->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, condicional3->chamadas, condicional3_C4->token, strlen(condicional3_C4->token), condicional3_C4);

    TransicaoChamada *condicional3_C5 = malloc(sizeof(TransicaoChamada));
    condicional3_C5->token = "INPUT";
    condicional3_C5->submaquina = "comandos";
    condicional3_C5->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, condicional3->chamadas, condicional3_C5->token, strlen(condicional3_C5->token), condicional3_C5);

    TransicaoChamada *condicional3_C6 = malloc(sizeof(TransicaoChamada));
    condicional3_C6->token = "OUTPUT";
    condicional3_C6->submaquina = "comandos";
    condicional3_C6->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, condicional3->chamadas, condicional3_C6->token, strlen(condicional3_C6->token), condicional3_C6);


    Estado *condicional4 = malloc(sizeof(Estado));
    condicional4->transicoes = NULL;
    condicional4->chamadas = NULL;
    condicional4->estado = 4;
    HASH_ADD_INT(condicional->estadosTransicoes, estado, condicional4);


    Transicao *condicional4_T1 = malloc(sizeof(Transicao));
    condicional4_T1->token = "END";
    condicional4_T1->estadoResultado = 5;
    HASH_ADD_KEYPTR(hh, condicional4->transicoes, condicional4_T1->token, strlen(condicional4_T1->token), condicional4_T1);



    Estado *condicional5 = malloc(sizeof(Estado));
    condicional5->transicoes = NULL;
    condicional5->chamadas = NULL;
    condicional5->estado = 5;
    HASH_ADD_INT(condicional->estadosTransicoes, estado, condicional5);


    Transicao *condicional5_T1 = malloc(sizeof(Transicao));
    condicional5_T1->token = "IF";
    condicional5_T1->estadoResultado = 6;
    HASH_ADD_KEYPTR(hh, condicional5->transicoes, condicional5_T1->token, strlen(condicional5_T1->token), condicional5_T1);



    Estado *condicional6 = malloc(sizeof(Estado));
    condicional6->transicoes = NULL;
    condicional6->chamadas = NULL;
    condicional6->estado = 6;
    HASH_ADD_INT(condicional->estadosTransicoes, estado, condicional6);


    Transicao *condicional6_T1 = malloc(sizeof(Transicao));
    condicional6_T1->token = ";";
    condicional6_T1->estadoResultado = 7;
    HASH_ADD_KEYPTR(hh, condicional6->transicoes, condicional6_T1->token, strlen(condicional6_T1->token), condicional6_T1);




    HASH_ADD_KEYPTR(hh, ape->automatos, condicional->title, strlen(condicional->title), condicional);

    /* iterativo */

    Automato *iterativo = malloc(sizeof(Automato));
    iterativo->estadosTransicoes = NULL;
    iterativo->title = "iterativo";
    iterativo->estado = 0;
    utarray_new(iterativo->estadosFinais, &ut_int_icd);



    push_tmp = 7; utarray_push_back(iterativo->estadosFinais, &push_tmp);



    Estado *iterativo0 = malloc(sizeof(Estado));
    iterativo0->transicoes = NULL;
    iterativo0->chamadas = NULL;
    iterativo0->estado = 0;
    HASH_ADD_INT(iterativo->estadosTransicoes, estado, iterativo0);


    Transicao *iterativo0_T1 = malloc(sizeof(Transicao));
    iterativo0_T1->token = "WHILE";
    iterativo0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, iterativo0->transicoes, iterativo0_T1->token, strlen(iterativo0_T1->token), iterativo0_T1);



    Estado *iterativo1 = malloc(sizeof(Estado));
    iterativo1->transicoes = NULL;
    iterativo1->chamadas = NULL;
    iterativo1->estado = 1;
    HASH_ADD_INT(iterativo->estadosTransicoes, estado, iterativo1);



    TransicaoChamada *iterativo1_C1 = malloc(sizeof(TransicaoChamada));
    iterativo1_C1->token = "(";
    iterativo1_C1->submaquina = "expressao";
    iterativo1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, iterativo1->chamadas, iterativo1_C1->token, strlen(iterativo1_C1->token), iterativo1_C1);

    TransicaoChamada *iterativo1_C2 = malloc(sizeof(TransicaoChamada));
    iterativo1_C2->token = "id";
    iterativo1_C2->submaquina = "expressao";
    iterativo1_C2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, iterativo1->chamadas, iterativo1_C2->token, strlen(iterativo1_C2->token), iterativo1_C2);

    TransicaoChamada *iterativo1_C3 = malloc(sizeof(TransicaoChamada));
    iterativo1_C3->token = "#f";
    iterativo1_C3->submaquina = "expressao";
    iterativo1_C3->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, iterativo1->chamadas, iterativo1_C3->token, strlen(iterativo1_C3->token), iterativo1_C3);

    TransicaoChamada *iterativo1_C4 = malloc(sizeof(TransicaoChamada));
    iterativo1_C4->token = "numero";
    iterativo1_C4->submaquina = "expressao";
    iterativo1_C4->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, iterativo1->chamadas, iterativo1_C4->token, strlen(iterativo1_C4->token), iterativo1_C4);

    TransicaoChamada *iterativo1_C5 = malloc(sizeof(TransicaoChamada));
    iterativo1_C5->token = "#t";
    iterativo1_C5->submaquina = "expressao";
    iterativo1_C5->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, iterativo1->chamadas, iterativo1_C5->token, strlen(iterativo1_C5->token), iterativo1_C5);


    Estado *iterativo2 = malloc(sizeof(Estado));
    iterativo2->transicoes = NULL;
    iterativo2->chamadas = NULL;
    iterativo2->estado = 2;
    HASH_ADD_INT(iterativo->estadosTransicoes, estado, iterativo2);


    Transicao *iterativo2_T1 = malloc(sizeof(Transicao));
    iterativo2_T1->token = "LOOP";
    iterativo2_T1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, iterativo2->transicoes, iterativo2_T1->token, strlen(iterativo2_T1->token), iterativo2_T1);



    Estado *iterativo3 = malloc(sizeof(Estado));
    iterativo3->transicoes = NULL;
    iterativo3->chamadas = NULL;
    iterativo3->estado = 3;
    HASH_ADD_INT(iterativo->estadosTransicoes, estado, iterativo3);



    TransicaoChamada *iterativo3_C1 = malloc(sizeof(TransicaoChamada));
    iterativo3_C1->token = "IF";
    iterativo3_C1->submaquina = "comandos";
    iterativo3_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, iterativo3->chamadas, iterativo3_C1->token, strlen(iterativo3_C1->token), iterativo3_C1);

    TransicaoChamada *iterativo3_C2 = malloc(sizeof(TransicaoChamada));
    iterativo3_C2->token = "CALL";
    iterativo3_C2->submaquina = "comandos";
    iterativo3_C2->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, iterativo3->chamadas, iterativo3_C2->token, strlen(iterativo3_C2->token), iterativo3_C2);

    TransicaoChamada *iterativo3_C3 = malloc(sizeof(TransicaoChamada));
    iterativo3_C3->token = "WHILE";
    iterativo3_C3->submaquina = "comandos";
    iterativo3_C3->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, iterativo3->chamadas, iterativo3_C3->token, strlen(iterativo3_C3->token), iterativo3_C3);

    TransicaoChamada *iterativo3_C4 = malloc(sizeof(TransicaoChamada));
    iterativo3_C4->token = "id";
    iterativo3_C4->submaquina = "comandos";
    iterativo3_C4->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, iterativo3->chamadas, iterativo3_C4->token, strlen(iterativo3_C4->token), iterativo3_C4);

    TransicaoChamada *iterativo3_C5 = malloc(sizeof(TransicaoChamada));
    iterativo3_C5->token = "INPUT";
    iterativo3_C5->submaquina = "comandos";
    iterativo3_C5->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, iterativo3->chamadas, iterativo3_C5->token, strlen(iterativo3_C5->token), iterativo3_C5);

    TransicaoChamada *iterativo3_C6 = malloc(sizeof(TransicaoChamada));
    iterativo3_C6->token = "OUTPUT";
    iterativo3_C6->submaquina = "comandos";
    iterativo3_C6->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, iterativo3->chamadas, iterativo3_C6->token, strlen(iterativo3_C6->token), iterativo3_C6);


    Estado *iterativo4 = malloc(sizeof(Estado));
    iterativo4->transicoes = NULL;
    iterativo4->chamadas = NULL;
    iterativo4->estado = 4;
    HASH_ADD_INT(iterativo->estadosTransicoes, estado, iterativo4);


    Transicao *iterativo4_T1 = malloc(sizeof(Transicao));
    iterativo4_T1->token = "END";
    iterativo4_T1->estadoResultado = 5;
    HASH_ADD_KEYPTR(hh, iterativo4->transicoes, iterativo4_T1->token, strlen(iterativo4_T1->token), iterativo4_T1);



    Estado *iterativo5 = malloc(sizeof(Estado));
    iterativo5->transicoes = NULL;
    iterativo5->chamadas = NULL;
    iterativo5->estado = 5;
    HASH_ADD_INT(iterativo->estadosTransicoes, estado, iterativo5);


    Transicao *iterativo5_T1 = malloc(sizeof(Transicao));
    iterativo5_T1->token = "LOOP";
    iterativo5_T1->estadoResultado = 6;
    HASH_ADD_KEYPTR(hh, iterativo5->transicoes, iterativo5_T1->token, strlen(iterativo5_T1->token), iterativo5_T1);



    Estado *iterativo6 = malloc(sizeof(Estado));
    iterativo6->transicoes = NULL;
    iterativo6->chamadas = NULL;
    iterativo6->estado = 6;
    HASH_ADD_INT(iterativo->estadosTransicoes, estado, iterativo6);


    Transicao *iterativo6_T1 = malloc(sizeof(Transicao));
    iterativo6_T1->token = ";";
    iterativo6_T1->estadoResultado = 7;
    HASH_ADD_KEYPTR(hh, iterativo6->transicoes, iterativo6_T1->token, strlen(iterativo6_T1->token), iterativo6_T1);




    HASH_ADD_KEYPTR(hh, ape->automatos, iterativo->title, strlen(iterativo->title), iterativo);

    /* saida */

    Automato *saida = malloc(sizeof(Automato));
    saida->estadosTransicoes = NULL;
    saida->title = "saida";
    saida->estado = 0;
    utarray_new(saida->estadosFinais, &ut_int_icd);



    push_tmp = 3; utarray_push_back(saida->estadosFinais, &push_tmp);



    Estado *saida0 = malloc(sizeof(Estado));
    saida0->transicoes = NULL;
    saida0->chamadas = NULL;
    saida0->estado = 0;
    HASH_ADD_INT(saida->estadosTransicoes, estado, saida0);


    Transicao *saida0_T1 = malloc(sizeof(Transicao));
    saida0_T1->token = "OUTPUT";
    saida0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, saida0->transicoes, saida0_T1->token, strlen(saida0_T1->token), saida0_T1);



    Estado *saida1 = malloc(sizeof(Estado));
    saida1->transicoes = NULL;
    saida1->chamadas = NULL;
    saida1->estado = 1;
    HASH_ADD_INT(saida->estadosTransicoes, estado, saida1);



    TransicaoChamada *saida1_C1 = malloc(sizeof(TransicaoChamada));
    saida1_C1->token = "id";
    saida1_C1->submaquina = "id";
    saida1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, saida1->chamadas, saida1_C1->token, strlen(saida1_C1->token), saida1_C1);


    Estado *saida2 = malloc(sizeof(Estado));
    saida2->transicoes = NULL;
    saida2->chamadas = NULL;
    saida2->estado = 2;
    HASH_ADD_INT(saida->estadosTransicoes, estado, saida2);


    Transicao *saida2_T1 = malloc(sizeof(Transicao));
    saida2_T1->token = ";";
    saida2_T1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, saida2->transicoes, saida2_T1->token, strlen(saida2_T1->token), saida2_T1);




    HASH_ADD_KEYPTR(hh, ape->automatos, saida->title, strlen(saida->title), saida);

    /* entrada */

    Automato *entrada = malloc(sizeof(Automato));
    entrada->estadosTransicoes = NULL;
    entrada->title = "entrada";
    entrada->estado = 0;
    utarray_new(entrada->estadosFinais, &ut_int_icd);



    push_tmp = 3; utarray_push_back(entrada->estadosFinais, &push_tmp);



    Estado *entrada0 = malloc(sizeof(Estado));
    entrada0->transicoes = NULL;
    entrada0->chamadas = NULL;
    entrada0->estado = 0;
    HASH_ADD_INT(entrada->estadosTransicoes, estado, entrada0);


    Transicao *entrada0_T1 = malloc(sizeof(Transicao));
    entrada0_T1->token = "INPUT";
    entrada0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, entrada0->transicoes, entrada0_T1->token, strlen(entrada0_T1->token), entrada0_T1);



    Estado *entrada1 = malloc(sizeof(Estado));
    entrada1->transicoes = NULL;
    entrada1->chamadas = NULL;
    entrada1->estado = 1;
    HASH_ADD_INT(entrada->estadosTransicoes, estado, entrada1);



    TransicaoChamada *entrada1_C1 = malloc(sizeof(TransicaoChamada));
    entrada1_C1->token = "id";
    entrada1_C1->submaquina = "id";
    entrada1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, entrada1->chamadas, entrada1_C1->token, strlen(entrada1_C1->token), entrada1_C1);


    Estado *entrada2 = malloc(sizeof(Estado));
    entrada2->transicoes = NULL;
    entrada2->chamadas = NULL;
    entrada2->estado = 2;
    HASH_ADD_INT(entrada->estadosTransicoes, estado, entrada2);


    Transicao *entrada2_T1 = malloc(sizeof(Transicao));
    entrada2_T1->token = ",";
    entrada2_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, entrada2->transicoes, entrada2_T1->token, strlen(entrada2_T1->token), entrada2_T1);

    Transicao *entrada2_T2 = malloc(sizeof(Transicao));
    entrada2_T2->token = ";";
    entrada2_T2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, entrada2->transicoes, entrada2_T2->token, strlen(entrada2_T2->token), entrada2_T2);




    HASH_ADD_KEYPTR(hh, ape->automatos, entrada->title, strlen(entrada->title), entrada);


    return ape;
}
