/**
 * This file was generated using Roro's parser
 * which parses language description in Wirth Notation into a Stack Automata in C.
 * https://github.com/rogerioyuuki/poli-github/tree/master/compiladores/entrega3/syntax
 *
 * Thanks [Roro](https://github.com/rogerioyuuki)!
 */

#include "ape.h"
#include "../lib/utarray.h"
#include "../lib/uthash.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/******************************/
/*          WARNING           */
/* This file is autogenerated */
/*                            */
/******************************/

void Automato_copy(void *_dst, const void *_src) {
  Automato *dst = (Automato*)_dst, *src = (Automato*)_src;
  dst->title = src->title;
  dst->estado = src->estado;

  dst->estadosTransicoes = src->estadosTransicoes;
  dst->estadosFinais = src->estadosFinais;
}

UT_icd Automato_icd = {sizeof(Automato), NULL, Automato_copy, NULL};

APE *create_ape() {
    int push_tmp;

    /* Initialize APE */
    APE * ape = malloc(sizeof(APE));
    ape->automatos = NULL;
    utarray_new(ape->pilha, &Automato_icd);



    /* PROGRAMA */

    Automato *PROGRAMA = malloc(sizeof(Automato));
    PROGRAMA->estadosTransicoes = NULL;
    PROGRAMA->title = "PROGRAMA";
    PROGRAMA->estado = 0;
    utarray_new(PROGRAMA->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(PROGRAMA->estadosFinais, &push_tmp);



    Estado *PROGRAMA0 = malloc(sizeof(Estado));
    PROGRAMA0->transicoes = NULL;
    PROGRAMA0->chamadas = NULL;
    PROGRAMA0->estado = 0;
    HASH_ADD_INT(PROGRAMA->estadosTransicoes, estado, PROGRAMA0);



    TransicaoChamada *PROGRAMA0_C1 = malloc(sizeof(TransicaoChamada));
    PROGRAMA0_C1->token = "numero";
    PROGRAMA0_C1->submaquina = "comando";
    PROGRAMA0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, PROGRAMA0->chamadas, PROGRAMA0_C1->token, strlen(PROGRAMA0_C1->token), PROGRAMA0_C1);

    TransicaoChamada *PROGRAMA0_C2 = malloc(sizeof(TransicaoChamada));
    PROGRAMA0_C2->token = "stackId";
    PROGRAMA0_C2->submaquina = "comando";
    PROGRAMA0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, PROGRAMA0->chamadas, PROGRAMA0_C2->token, strlen(PROGRAMA0_C2->token), PROGRAMA0_C2);

    TransicaoChamada *PROGRAMA0_C3 = malloc(sizeof(TransicaoChamada));
    PROGRAMA0_C3->token = "(";
    PROGRAMA0_C3->submaquina = "comando";
    PROGRAMA0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, PROGRAMA0->chamadas, PROGRAMA0_C3->token, strlen(PROGRAMA0_C3->token), PROGRAMA0_C3);


    Estado *PROGRAMA1 = malloc(sizeof(Estado));
    PROGRAMA1->transicoes = NULL;
    PROGRAMA1->chamadas = NULL;
    PROGRAMA1->estado = 1;
    HASH_ADD_INT(PROGRAMA->estadosTransicoes, estado, PROGRAMA1);



    TransicaoChamada *PROGRAMA1_C1 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C1->token = "numero";
    PROGRAMA1_C1->submaquina = "comando";
    PROGRAMA1_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C1->token, strlen(PROGRAMA1_C1->token), PROGRAMA1_C1);

    TransicaoChamada *PROGRAMA1_C2 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C2->token = "stackId";
    PROGRAMA1_C2->submaquina = "comando";
    PROGRAMA1_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C2->token, strlen(PROGRAMA1_C2->token), PROGRAMA1_C2);

    TransicaoChamada *PROGRAMA1_C3 = malloc(sizeof(TransicaoChamada));
    PROGRAMA1_C3->token = "(";
    PROGRAMA1_C3->submaquina = "comando";
    PROGRAMA1_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, PROGRAMA1->chamadas, PROGRAMA1_C3->token, strlen(PROGRAMA1_C3->token), PROGRAMA1_C3);



    HASH_ADD_KEYPTR(hh, ape->automatos, PROGRAMA->title, strlen(PROGRAMA->title), PROGRAMA);


    ape->automatoAtual = PROGRAMA;



    /* comando */

    Automato *comando = malloc(sizeof(Automato));
    comando->estadosTransicoes = NULL;
    comando->title = "comando";
    comando->estado = 0;
    utarray_new(comando->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(comando->estadosFinais, &push_tmp);



    Estado *comando0 = malloc(sizeof(Estado));
    comando0->transicoes = NULL;
    comando0->chamadas = NULL;
    comando0->estado = 0;
    HASH_ADD_INT(comando->estadosTransicoes, estado, comando0);



    TransicaoChamada *comando0_C1 = malloc(sizeof(TransicaoChamada));
    comando0_C1->token = "(";
    comando0_C1->submaquina = "loop";
    comando0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comando0->chamadas, comando0_C1->token, strlen(comando0_C1->token), comando0_C1);

    TransicaoChamada *comando0_C2 = malloc(sizeof(TransicaoChamada));
    comando0_C2->token = "numero";
    comando0_C2->submaquina = "expressao";
    comando0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comando0->chamadas, comando0_C2->token, strlen(comando0_C2->token), comando0_C2);

    TransicaoChamada *comando0_C3 = malloc(sizeof(TransicaoChamada));
    comando0_C3->token = "stackId";
    comando0_C3->submaquina = "expressao";
    comando0_C3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, comando0->chamadas, comando0_C3->token, strlen(comando0_C3->token), comando0_C3);



    HASH_ADD_KEYPTR(hh, ape->automatos, comando->title, strlen(comando->title), comando);

    /* loop */

    Automato *loop = malloc(sizeof(Automato));
    loop->estadosTransicoes = NULL;
    loop->title = "loop";
    loop->estado = 0;
    utarray_new(loop->estadosFinais, &ut_int_icd);



    push_tmp = 4; utarray_push_back(loop->estadosFinais, &push_tmp);



    Estado *loop0 = malloc(sizeof(Estado));
    loop0->transicoes = NULL;
    loop0->chamadas = NULL;
    loop0->estado = 0;
    HASH_ADD_INT(loop->estadosTransicoes, estado, loop0);


    Transicao *loop0_T1 = malloc(sizeof(Transicao));
    loop0_T1->token = "(";
    loop0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, loop0->transicoes, loop0_T1->token, strlen(loop0_T1->token), loop0_T1);



    Estado *loop1 = malloc(sizeof(Estado));
    loop1->transicoes = NULL;
    loop1->chamadas = NULL;
    loop1->estado = 1;
    HASH_ADD_INT(loop->estadosTransicoes, estado, loop1);



    TransicaoChamada *loop1_C1 = malloc(sizeof(TransicaoChamada));
    loop1_C1->token = "stackId";
    loop1_C1->submaquina = "stackId";
    loop1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, loop1->chamadas, loop1_C1->token, strlen(loop1_C1->token), loop1_C1);


    Estado *loop2 = malloc(sizeof(Estado));
    loop2->transicoes = NULL;
    loop2->chamadas = NULL;
    loop2->estado = 2;
    HASH_ADD_INT(loop->estadosTransicoes, estado, loop2);


    Transicao *loop2_T1 = malloc(sizeof(Transicao));
    loop2_T1->token = ")";
    loop2_T1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, loop2->transicoes, loop2_T1->token, strlen(loop2_T1->token), loop2_T1);


    TransicaoChamada *loop2_C1 = malloc(sizeof(TransicaoChamada));
    loop2_C1->token = "-";
    loop2_C1->submaquina = "concatStackOp";
    loop2_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop2->chamadas, loop2_C1->token, strlen(loop2_C1->token), loop2_C1);

    TransicaoChamada *loop2_C2 = malloc(sizeof(TransicaoChamada));
    loop2_C2->token = "?";
    loop2_C2->submaquina = "concatStackOp";
    loop2_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop2->chamadas, loop2_C2->token, strlen(loop2_C2->token), loop2_C2);

    TransicaoChamada *loop2_C3 = malloc(sizeof(TransicaoChamada));
    loop2_C3->token = ">";
    loop2_C3->submaquina = "concatStackOp";
    loop2_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop2->chamadas, loop2_C3->token, strlen(loop2_C3->token), loop2_C3);

    TransicaoChamada *loop2_C4 = malloc(sizeof(TransicaoChamada));
    loop2_C4->token = "<";
    loop2_C4->submaquina = "concatStackOp";
    loop2_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop2->chamadas, loop2_C4->token, strlen(loop2_C4->token), loop2_C4);

    TransicaoChamada *loop2_C5 = malloc(sizeof(TransicaoChamada));
    loop2_C5->token = "+";
    loop2_C5->submaquina = "concatStackOp";
    loop2_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop2->chamadas, loop2_C5->token, strlen(loop2_C5->token), loop2_C5);

    TransicaoChamada *loop2_C6 = malloc(sizeof(TransicaoChamada));
    loop2_C6->token = "numero";
    loop2_C6->submaquina = "comando";
    loop2_C6->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop2->chamadas, loop2_C6->token, strlen(loop2_C6->token), loop2_C6);

    TransicaoChamada *loop2_C7 = malloc(sizeof(TransicaoChamada));
    loop2_C7->token = "stackId";
    loop2_C7->submaquina = "comando";
    loop2_C7->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop2->chamadas, loop2_C7->token, strlen(loop2_C7->token), loop2_C7);

    TransicaoChamada *loop2_C8 = malloc(sizeof(TransicaoChamada));
    loop2_C8->token = "(";
    loop2_C8->submaquina = "comando";
    loop2_C8->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop2->chamadas, loop2_C8->token, strlen(loop2_C8->token), loop2_C8);


    Estado *loop3 = malloc(sizeof(Estado));
    loop3->transicoes = NULL;
    loop3->chamadas = NULL;
    loop3->estado = 3;
    HASH_ADD_INT(loop->estadosTransicoes, estado, loop3);


    Transicao *loop3_T1 = malloc(sizeof(Transicao));
    loop3_T1->token = ")";
    loop3_T1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, loop3->transicoes, loop3_T1->token, strlen(loop3_T1->token), loop3_T1);


    TransicaoChamada *loop3_C1 = malloc(sizeof(TransicaoChamada));
    loop3_C1->token = "numero";
    loop3_C1->submaquina = "comando";
    loop3_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop3->chamadas, loop3_C1->token, strlen(loop3_C1->token), loop3_C1);

    TransicaoChamada *loop3_C2 = malloc(sizeof(TransicaoChamada));
    loop3_C2->token = "stackId";
    loop3_C2->submaquina = "comando";
    loop3_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop3->chamadas, loop3_C2->token, strlen(loop3_C2->token), loop3_C2);

    TransicaoChamada *loop3_C3 = malloc(sizeof(TransicaoChamada));
    loop3_C3->token = "(";
    loop3_C3->submaquina = "comando";
    loop3_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, loop3->chamadas, loop3_C3->token, strlen(loop3_C3->token), loop3_C3);



    HASH_ADD_KEYPTR(hh, ape->automatos, loop->title, strlen(loop->title), loop);

    /* expressao */

    Automato *expressao = malloc(sizeof(Automato));
    expressao->estadosTransicoes = NULL;
    expressao->title = "expressao";
    expressao->estado = 0;
    utarray_new(expressao->estadosFinais, &ut_int_icd);



    push_tmp = 1; utarray_push_back(expressao->estadosFinais, &push_tmp);



    Estado *expressao0 = malloc(sizeof(Estado));
    expressao0->transicoes = NULL;
    expressao0->chamadas = NULL;
    expressao0->estado = 0;
    HASH_ADD_INT(expressao->estadosTransicoes, estado, expressao0);



    TransicaoChamada *expressao0_C1 = malloc(sizeof(TransicaoChamada));
    expressao0_C1->token = "stackId";
    expressao0_C1->submaquina = "expressaoStack";
    expressao0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao0->chamadas, expressao0_C1->token, strlen(expressao0_C1->token), expressao0_C1);

    TransicaoChamada *expressao0_C2 = malloc(sizeof(TransicaoChamada));
    expressao0_C2->token = "numero";
    expressao0_C2->submaquina = "expressaoNum";
    expressao0_C2->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressao0->chamadas, expressao0_C2->token, strlen(expressao0_C2->token), expressao0_C2);



    HASH_ADD_KEYPTR(hh, ape->automatos, expressao->title, strlen(expressao->title), expressao);

    /* expressaoStack */

    Automato *expressaoStack = malloc(sizeof(Automato));
    expressaoStack->estadosTransicoes = NULL;
    expressaoStack->title = "expressaoStack";
    expressaoStack->estado = 0;
    utarray_new(expressaoStack->estadosFinais, &ut_int_icd);



    push_tmp = 2; utarray_push_back(expressaoStack->estadosFinais, &push_tmp);



    Estado *expressaoStack0 = malloc(sizeof(Estado));
    expressaoStack0->transicoes = NULL;
    expressaoStack0->chamadas = NULL;
    expressaoStack0->estado = 0;
    HASH_ADD_INT(expressaoStack->estadosTransicoes, estado, expressaoStack0);



    TransicaoChamada *expressaoStack0_C1 = malloc(sizeof(TransicaoChamada));
    expressaoStack0_C1->token = "stackId";
    expressaoStack0_C1->submaquina = "stackId";
    expressaoStack0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressaoStack0->chamadas, expressaoStack0_C1->token, strlen(expressaoStack0_C1->token), expressaoStack0_C1);


    Estado *expressaoStack1 = malloc(sizeof(Estado));
    expressaoStack1->transicoes = NULL;
    expressaoStack1->chamadas = NULL;
    expressaoStack1->estado = 1;
    HASH_ADD_INT(expressaoStack->estadosTransicoes, estado, expressaoStack1);



    TransicaoChamada *expressaoStack1_C1 = malloc(sizeof(TransicaoChamada));
    expressaoStack1_C1->token = "-";
    expressaoStack1_C1->submaquina = "concatStackOp";
    expressaoStack1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, expressaoStack1->chamadas, expressaoStack1_C1->token, strlen(expressaoStack1_C1->token), expressaoStack1_C1);

    TransicaoChamada *expressaoStack1_C2 = malloc(sizeof(TransicaoChamada));
    expressaoStack1_C2->token = "?";
    expressaoStack1_C2->submaquina = "concatStackOp";
    expressaoStack1_C2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, expressaoStack1->chamadas, expressaoStack1_C2->token, strlen(expressaoStack1_C2->token), expressaoStack1_C2);

    TransicaoChamada *expressaoStack1_C3 = malloc(sizeof(TransicaoChamada));
    expressaoStack1_C3->token = ">";
    expressaoStack1_C3->submaquina = "concatStackOp";
    expressaoStack1_C3->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, expressaoStack1->chamadas, expressaoStack1_C3->token, strlen(expressaoStack1_C3->token), expressaoStack1_C3);

    TransicaoChamada *expressaoStack1_C4 = malloc(sizeof(TransicaoChamada));
    expressaoStack1_C4->token = "<";
    expressaoStack1_C4->submaquina = "concatStackOp";
    expressaoStack1_C4->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, expressaoStack1->chamadas, expressaoStack1_C4->token, strlen(expressaoStack1_C4->token), expressaoStack1_C4);

    TransicaoChamada *expressaoStack1_C5 = malloc(sizeof(TransicaoChamada));
    expressaoStack1_C5->token = "+";
    expressaoStack1_C5->submaquina = "concatStackOp";
    expressaoStack1_C5->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, expressaoStack1->chamadas, expressaoStack1_C5->token, strlen(expressaoStack1_C5->token), expressaoStack1_C5);



    HASH_ADD_KEYPTR(hh, ape->automatos, expressaoStack->title, strlen(expressaoStack->title), expressaoStack);

    /* expressaoNum */

    Automato *expressaoNum = malloc(sizeof(Automato));
    expressaoNum->estadosTransicoes = NULL;
    expressaoNum->title = "expressaoNum";
    expressaoNum->estado = 0;
    utarray_new(expressaoNum->estadosFinais, &ut_int_icd);



    push_tmp = 2; utarray_push_back(expressaoNum->estadosFinais, &push_tmp);



    Estado *expressaoNum0 = malloc(sizeof(Estado));
    expressaoNum0->transicoes = NULL;
    expressaoNum0->chamadas = NULL;
    expressaoNum0->estado = 0;
    HASH_ADD_INT(expressaoNum->estadosTransicoes, estado, expressaoNum0);



    TransicaoChamada *expressaoNum0_C1 = malloc(sizeof(TransicaoChamada));
    expressaoNum0_C1->token = "numero";
    expressaoNum0_C1->submaquina = "numero";
    expressaoNum0_C1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, expressaoNum0->chamadas, expressaoNum0_C1->token, strlen(expressaoNum0_C1->token), expressaoNum0_C1);


    Estado *expressaoNum1 = malloc(sizeof(Estado));
    expressaoNum1->transicoes = NULL;
    expressaoNum1->chamadas = NULL;
    expressaoNum1->estado = 1;
    HASH_ADD_INT(expressaoNum->estadosTransicoes, estado, expressaoNum1);



    TransicaoChamada *expressaoNum1_C1 = malloc(sizeof(TransicaoChamada));
    expressaoNum1_C1->token = ">";
    expressaoNum1_C1->submaquina = "concatNumOp";
    expressaoNum1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, expressaoNum1->chamadas, expressaoNum1_C1->token, strlen(expressaoNum1_C1->token), expressaoNum1_C1);



    HASH_ADD_KEYPTR(hh, ape->automatos, expressaoNum->title, strlen(expressaoNum->title), expressaoNum);

    /* concatStackOp */

    Automato *concatStackOp = malloc(sizeof(Automato));
    concatStackOp->estadosTransicoes = NULL;
    concatStackOp->title = "concatStackOp";
    concatStackOp->estado = 0;
    utarray_new(concatStackOp->estadosFinais, &ut_int_icd);



    push_tmp = 3; utarray_push_back(concatStackOp->estadosFinais, &push_tmp);

    push_tmp = 4; utarray_push_back(concatStackOp->estadosFinais, &push_tmp);

    push_tmp = 5; utarray_push_back(concatStackOp->estadosFinais, &push_tmp);



    Estado *concatStackOp0 = malloc(sizeof(Estado));
    concatStackOp0->transicoes = NULL;
    concatStackOp0->chamadas = NULL;
    concatStackOp0->estado = 0;
    HASH_ADD_INT(concatStackOp->estadosTransicoes, estado, concatStackOp0);


    Transicao *concatStackOp0_T1 = malloc(sizeof(Transicao));
    concatStackOp0_T1->token = "<";
    concatStackOp0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, concatStackOp0->transicoes, concatStackOp0_T1->token, strlen(concatStackOp0_T1->token), concatStackOp0_T1);

    Transicao *concatStackOp0_T2 = malloc(sizeof(Transicao));
    concatStackOp0_T2->token = ">";
    concatStackOp0_T2->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, concatStackOp0->transicoes, concatStackOp0_T2->token, strlen(concatStackOp0_T2->token), concatStackOp0_T2);

    Transicao *concatStackOp0_T3 = malloc(sizeof(Transicao));
    concatStackOp0_T3->token = "+";
    concatStackOp0_T3->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, concatStackOp0->transicoes, concatStackOp0_T3->token, strlen(concatStackOp0_T3->token), concatStackOp0_T3);

    Transicao *concatStackOp0_T4 = malloc(sizeof(Transicao));
    concatStackOp0_T4->token = "-";
    concatStackOp0_T4->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, concatStackOp0->transicoes, concatStackOp0_T4->token, strlen(concatStackOp0_T4->token), concatStackOp0_T4);

    Transicao *concatStackOp0_T5 = malloc(sizeof(Transicao));
    concatStackOp0_T5->token = "?";
    concatStackOp0_T5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatStackOp0->transicoes, concatStackOp0_T5->token, strlen(concatStackOp0_T5->token), concatStackOp0_T5);



    Estado *concatStackOp1 = malloc(sizeof(Estado));
    concatStackOp1->transicoes = NULL;
    concatStackOp1->chamadas = NULL;
    concatStackOp1->estado = 1;
    HASH_ADD_INT(concatStackOp->estadosTransicoes, estado, concatStackOp1);



    TransicaoChamada *concatStackOp1_C1 = malloc(sizeof(TransicaoChamada));
    concatStackOp1_C1->token = "stackId";
    concatStackOp1_C1->submaquina = "stackId";
    concatStackOp1_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, concatStackOp1->chamadas, concatStackOp1_C1->token, strlen(concatStackOp1_C1->token), concatStackOp1_C1);

    TransicaoChamada *concatStackOp1_C2 = malloc(sizeof(TransicaoChamada));
    concatStackOp1_C2->token = "numero";
    concatStackOp1_C2->submaquina = "numero";
    concatStackOp1_C2->estadoResultado = 5;
    HASH_ADD_KEYPTR(hh, concatStackOp1->chamadas, concatStackOp1_C2->token, strlen(concatStackOp1_C2->token), concatStackOp1_C2);


    Estado *concatStackOp2 = malloc(sizeof(Estado));
    concatStackOp2->transicoes = NULL;
    concatStackOp2->chamadas = NULL;
    concatStackOp2->estado = 2;
    HASH_ADD_INT(concatStackOp->estadosTransicoes, estado, concatStackOp2);



    TransicaoChamada *concatStackOp2_C1 = malloc(sizeof(TransicaoChamada));
    concatStackOp2_C1->token = "stackId";
    concatStackOp2_C1->submaquina = "stackId";
    concatStackOp2_C1->estadoResultado = 4;
    HASH_ADD_KEYPTR(hh, concatStackOp2->chamadas, concatStackOp2_C1->token, strlen(concatStackOp2_C1->token), concatStackOp2_C1);


    Estado *concatStackOp4 = malloc(sizeof(Estado));
    concatStackOp4->transicoes = NULL;
    concatStackOp4->chamadas = NULL;
    concatStackOp4->estado = 4;
    HASH_ADD_INT(concatStackOp->estadosTransicoes, estado, concatStackOp4);



    TransicaoChamada *concatStackOp4_C1 = malloc(sizeof(TransicaoChamada));
    concatStackOp4_C1->token = "-";
    concatStackOp4_C1->submaquina = "concatStackOp";
    concatStackOp4_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatStackOp4->chamadas, concatStackOp4_C1->token, strlen(concatStackOp4_C1->token), concatStackOp4_C1);

    TransicaoChamada *concatStackOp4_C2 = malloc(sizeof(TransicaoChamada));
    concatStackOp4_C2->token = "?";
    concatStackOp4_C2->submaquina = "concatStackOp";
    concatStackOp4_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatStackOp4->chamadas, concatStackOp4_C2->token, strlen(concatStackOp4_C2->token), concatStackOp4_C2);

    TransicaoChamada *concatStackOp4_C3 = malloc(sizeof(TransicaoChamada));
    concatStackOp4_C3->token = ">";
    concatStackOp4_C3->submaquina = "concatStackOp";
    concatStackOp4_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatStackOp4->chamadas, concatStackOp4_C3->token, strlen(concatStackOp4_C3->token), concatStackOp4_C3);

    TransicaoChamada *concatStackOp4_C4 = malloc(sizeof(TransicaoChamada));
    concatStackOp4_C4->token = "<";
    concatStackOp4_C4->submaquina = "concatStackOp";
    concatStackOp4_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatStackOp4->chamadas, concatStackOp4_C4->token, strlen(concatStackOp4_C4->token), concatStackOp4_C4);

    TransicaoChamada *concatStackOp4_C5 = malloc(sizeof(TransicaoChamada));
    concatStackOp4_C5->token = "+";
    concatStackOp4_C5->submaquina = "concatStackOp";
    concatStackOp4_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatStackOp4->chamadas, concatStackOp4_C5->token, strlen(concatStackOp4_C5->token), concatStackOp4_C5);


    Estado *concatStackOp5 = malloc(sizeof(Estado));
    concatStackOp5->transicoes = NULL;
    concatStackOp5->chamadas = NULL;
    concatStackOp5->estado = 5;
    HASH_ADD_INT(concatStackOp->estadosTransicoes, estado, concatStackOp5);



    TransicaoChamada *concatStackOp5_C1 = malloc(sizeof(TransicaoChamada));
    concatStackOp5_C1->token = ">";
    concatStackOp5_C1->submaquina = "concatNumOp";
    concatStackOp5_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatStackOp5->chamadas, concatStackOp5_C1->token, strlen(concatStackOp5_C1->token), concatStackOp5_C1);



    HASH_ADD_KEYPTR(hh, ape->automatos, concatStackOp->title, strlen(concatStackOp->title), concatStackOp);

    /* concatNumOp */

    Automato *concatNumOp = malloc(sizeof(Automato));
    concatNumOp->estadosTransicoes = NULL;
    concatNumOp->title = "concatNumOp";
    concatNumOp->estado = 0;
    utarray_new(concatNumOp->estadosFinais, &ut_int_icd);



    push_tmp = 2; utarray_push_back(concatNumOp->estadosFinais, &push_tmp);

    push_tmp = 3; utarray_push_back(concatNumOp->estadosFinais, &push_tmp);



    Estado *concatNumOp0 = malloc(sizeof(Estado));
    concatNumOp0->transicoes = NULL;
    concatNumOp0->chamadas = NULL;
    concatNumOp0->estado = 0;
    HASH_ADD_INT(concatNumOp->estadosTransicoes, estado, concatNumOp0);


    Transicao *concatNumOp0_T1 = malloc(sizeof(Transicao));
    concatNumOp0_T1->token = ">";
    concatNumOp0_T1->estadoResultado = 1;
    HASH_ADD_KEYPTR(hh, concatNumOp0->transicoes, concatNumOp0_T1->token, strlen(concatNumOp0_T1->token), concatNumOp0_T1);



    Estado *concatNumOp1 = malloc(sizeof(Estado));
    concatNumOp1->transicoes = NULL;
    concatNumOp1->chamadas = NULL;
    concatNumOp1->estado = 1;
    HASH_ADD_INT(concatNumOp->estadosTransicoes, estado, concatNumOp1);



    TransicaoChamada *concatNumOp1_C1 = malloc(sizeof(TransicaoChamada));
    concatNumOp1_C1->token = "stackId";
    concatNumOp1_C1->submaquina = "stackId";
    concatNumOp1_C1->estadoResultado = 2;
    HASH_ADD_KEYPTR(hh, concatNumOp1->chamadas, concatNumOp1_C1->token, strlen(concatNumOp1_C1->token), concatNumOp1_C1);


    Estado *concatNumOp2 = malloc(sizeof(Estado));
    concatNumOp2->transicoes = NULL;
    concatNumOp2->chamadas = NULL;
    concatNumOp2->estado = 2;
    HASH_ADD_INT(concatNumOp->estadosTransicoes, estado, concatNumOp2);



    TransicaoChamada *concatNumOp2_C1 = malloc(sizeof(TransicaoChamada));
    concatNumOp2_C1->token = "-";
    concatNumOp2_C1->submaquina = "concatStackOp";
    concatNumOp2_C1->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatNumOp2->chamadas, concatNumOp2_C1->token, strlen(concatNumOp2_C1->token), concatNumOp2_C1);

    TransicaoChamada *concatNumOp2_C2 = malloc(sizeof(TransicaoChamada));
    concatNumOp2_C2->token = "?";
    concatNumOp2_C2->submaquina = "concatStackOp";
    concatNumOp2_C2->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatNumOp2->chamadas, concatNumOp2_C2->token, strlen(concatNumOp2_C2->token), concatNumOp2_C2);

    TransicaoChamada *concatNumOp2_C3 = malloc(sizeof(TransicaoChamada));
    concatNumOp2_C3->token = ">";
    concatNumOp2_C3->submaquina = "concatStackOp";
    concatNumOp2_C3->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatNumOp2->chamadas, concatNumOp2_C3->token, strlen(concatNumOp2_C3->token), concatNumOp2_C3);

    TransicaoChamada *concatNumOp2_C4 = malloc(sizeof(TransicaoChamada));
    concatNumOp2_C4->token = "<";
    concatNumOp2_C4->submaquina = "concatStackOp";
    concatNumOp2_C4->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatNumOp2->chamadas, concatNumOp2_C4->token, strlen(concatNumOp2_C4->token), concatNumOp2_C4);

    TransicaoChamada *concatNumOp2_C5 = malloc(sizeof(TransicaoChamada));
    concatNumOp2_C5->token = "+";
    concatNumOp2_C5->submaquina = "concatStackOp";
    concatNumOp2_C5->estadoResultado = 3;
    HASH_ADD_KEYPTR(hh, concatNumOp2->chamadas, concatNumOp2_C5->token, strlen(concatNumOp2_C5->token), concatNumOp2_C5);



    HASH_ADD_KEYPTR(hh, ape->automatos, concatNumOp->title, strlen(concatNumOp->title), concatNumOp);


    return ape;
}
